### ISSUE TITLE
Add ability to remove projects from the Admn UI

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#103]
As of today a bunch of projects are available out-of-the-box in the web admin UI. It's a nice thing because people can immediately see what scava looks like. 
However when one wants to have their own instance configured, they want to be able to delete projects they don't want. Is it possible to add a "Delete" button in the list of projects?

**Comment by ambpro** [comment]
@borisbaldassari As the feature is implements, are you agree to close this ticket ?
