### ISSUE TITLE
Show list of connectors and parameters for project in Admin UI

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#104]
As of today there are 2 ways to create a project: importing it via an url and creating it from scratch, adding connectors manually. In both cases after saving the project **there is no way to know what connectors** are setup or to view their configuration. When investigating errors, it is fundamental to know the configuration of the project and possibly edit it.

**Comment by ambpro** [comment]
Hi @borisbaldassari, 
I fully agree with you to have an **edit** feature for the admin-ui projects and I am working on it.
FYI, the metric-providers are assigned to each analysis task configuration within one project.
To display them, you have just to hit `Execution Metrics` url and up! a popup will be opened with the metric-providers details configured on this task.

![analysis-task](https://user-images.githubusercontent.com/35226648/53031340-f307d580-346c-11e9-8729-765cad140880.PNG)

**Comment by borisbaldassari** [comment]
That looks very good, thank you Amin! Can't wait to see it in action.. :-)

**Comment by borisbaldassari** [comment]
Hi Amin, it's nice to have the list of metrics!
However this issue was about having the list of **connectors** defined on the project: e.g. bugzilla, git, jenkins, gerrit... with their parameters. Do you have plans to have it displayed?

**Comment by mhow2** [comment]
I am also in need of this feature, ie editing project sources properties.

**Comment by mhow2** [comment]
> I am working on it.

@ambpro I would be interested to know on which features you're working on. So we could have a better idea of what we can expect for the future.

**Comment by mhow2** [comment]
Still interested.

**Comment by borisbaldassari** [comment]
still up too. :-)

**Comment by ambpro** [comment]
> @ambpro I would be interested to know on which features you're working on. So we could have a better idea of what we can expect for the future.

@mhow2, I was working on the project edition feature which is available now on the admin-ui.

> However this issue was about having the list of connectors defined on the project: e.g. bugzilla, git, jenkins, gerrit... with their parameters. Do you have plans to have it displayed?

@borisbaldassari, the commit a542b37 should display the list of the connectors behind an existing project. Moreover, you could also edit the list of the connectors through the project's configuration page.

**Comment by borisbaldassari** [comment]
Works for me. @mhow2, can we close that now?
