### ISSUE TITLE
working with several workers

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#109]
Here is a screenshot of the situation I am observing in the Admin UI:
![screenshot_2019-02-13 crossminer administration](https://user-images.githubusercontent.com/9987241/52706164-0aceed80-2f85-11e9-8cb3-7de2728a788d.png)

As you can see, there are pending task that I am unable to assign to the free worker `w1`.

Here is how to reproduce.
- clone a copy of `scava-deployment` and edit the various files as stated in the README.
- additionally and in order to start from scratch, edit `oss-db/mongo-restore.sh` and comment line about restoring the dumps.
- you also need a persistent storage volume for oss-db to keep the data when re-creating/updating some the metric-platform container
- build and start the stack. At this point you should have one visible worker `w1`
- stop the stack
- edit docker-compose-build.yml, in service `oss-app` -> `entrypoint` property replace the  `-worker w1` by `-worker w2`
- start the stack. In the worker view you should now see both `w1` and `w2`
- add at least two projects to the platform with their related tasks.
- start at least two tasks 
- go to workers view. Here you should see something close to the screenshot I have provided. Hitting buttons w1/w2 in the pending task provides no result.

**Comment by mhow2** [comment]
@ambpro : could we have a feedback about it ? It would allow us to analyze projects faster.

**Comment by mhow2** [comment]
@ambpro, if you have an input it could ease the process for https://github.com/crossminer/scava-deployment/issues/49

**Comment by MarcioMateus** [comment]
Hi @mhow2 , I am not sure about this but I think that after all the steps you performed, you were only running one worker (`w2`).
You created structures in the database for 2 workers (`w1` and `w2`) but in the last time that you started the platform you only assigned "processing resources" to `w2`.

Thus this make sense? I also do not know how to have multiple workers running on the same instance of the metric-platform. Probably, to have 2 workers running in simultaneous you need to have 2 instances of the metric-platform running.

@ambpro  Please, correct me if I am wrong.

**Comment by mhow2** [comment]
Hi @MarcioMateus,

> Hi @mhow2 , I am not sure about this but I think that after all the steps you performed, you were only running one worker (`w2`).
> You created structures in the database for 2 workers (`w1` and `w2`) but in the last time that you started the platform you only assigned "processing resources" to `w2`.
> 
> Thus this make sense ?

Of course it makes sense, because it doesn't seem possible to have multiple `-worker` args. I agree with you, it's not logical.

> I also do not know how to have multiple workers running on the same instance of the metric-platform. Probably, to have 2 workers running in simultaneous you need to have 2 instances of the metric-platform running.
> 
> @ambpro Please, correct me if I am wrong.

Waiting @ambpro input about it.

**Comment by ambpro** [comment]
Hello @mhow2 @MarcioMateus , sorry for the late reply.
I tried to play with the scava-deployment stack and I confirm this behavior.
> Hi @mhow2 , I am not sure about this but I think that after all the steps you performed, you were only running one worker (w2).

Totally agree. In this case, just the `w2` worker is running on the metric-platform. 
As the 'docker-compose stop' stops the running containers including the `w1` process, restarting the scava-deployment stack will created a new worker on the metric-platform.

>You created structures in the database for 2 workers (w1 and w2) but in the last time that you started the platform you only assigned "processing resources" to w2.

Yes, the way in which a worker is started implied the persistence of its own data on the `scava-analysis` database. Even, the stack was stopped, the worker collection still here. Below, an example of the workers database collection while reproducing the issue.

![workers](https://user-images.githubusercontent.com/35226648/57451715-59c5af80-7262-11e9-8e9b-2f5157de8bbc.png)

I guess the only way to avoid this behavior is to run  `docker-compose down` instead of `docker-compose stop` which clean up all the containers.

>I also do not know how to have multiple workers running on the same instance of the metric-platform. Probably, to have 2 workers running in simultaneous you need to have 2 instances of the metric-platform running.

Agree with you. To launch more than one worker, we have to start at least two or more metric-platform's instances within the docker-compose entry-point config. This is what we do on the development env.

**Comment by mhow2** [comment]
> Totally agree. In this case, just the w2 worker is running on the metric-platform.

I understand. The step I have followed created w2 and that's all. But then I have two workers in the UI so I am in position to think that I have two workers available in the PF. It doesn't tell if they are both "online" - naively speaking but... I see two workers. If one can't take jobs for some reason maybe the UI should reflect that.

Now that everything is explained and agreed, can you please share an example of the modified docker-compose to run two instances of the MP ? That's not only for me, that's for documenting the project !

**Comment by ambpro** [comment]
@mhow2 

>But then I have two workers in the UI so I am in position to think that I have two workers available in the PF.

To avoid confusion, I think th best solution is to clean up the old workers trace from the database  while restarting the stack.

> can you please share an example of the modified docker-compose to run two instances of the MP?

I 'll try to implement it on docker and give you feedback asap!

**Comment by MarcioMateus** [comment]
We can probably update the `oss-slave` service to work as second worker when uncommented.

Let me test it.

**Comment by MarcioMateus** [comment]
@mhow2 @ambpro can you give a quick test to `multi-workers` branch in `scava-development`?
https://github.com/crossminer/scava-deployment/commit/25797f5027bdb385f07ce60f54c34ff05599aa81

I modified uncommented and modified the service `oss-slave` to start the worker `w2`. In my tests I was able to analyse two tasks in parallel.

**Comment by ambpro** [comment]
@MarcioMateus , crossminer/scava-deployment@25797f5 seems to be ok for me.

**Comment by mhow2** [comment]
Thank you both: I just tested that I am able to run two tasks in parallel as well.
Now, I think the documentation has to be updated. There is an existing empty section "Workers Configuration" at https://scava-docs.readthedocs.io/en/latest/installation-guide/docker-installation/

**Comment by mhow2** [comment]
Hi @ambpro, @MarcioMateus 
I see two things to do before closing this issue. The first one is to updated the documentation (see above) and the second is to check everything is ready-to-use in https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-build.yml and https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-dockerhub.yml

**Comment by mhow2** [comment]
I see the documentation has been updated, perfect ! Thanks
