### ISSUE TITLE
ProjectAnalyser not matching IdentifiersOfUses

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#115]
Hello,

I'm playing right now with the __ProjectAnalyser__ and, unless I'm wrong, it seems that it is not retrieving all the metrics dependencies, i.e. the __getIdentifiersOfUses()__.

In the method __splitIntoBranches__, more exactly in line 241 we have:

`IMetricProvider use = lookupMetricProviderById(metrics, id);`

where __metrics__ corresponds to the list of metrics that we are splitting and __id__ is the string regarding one of the metrics dependencies returned by __getIdentifiersOfUses()__.

Then in  __lookupMetricProviderById__, we look for a match between metrics and id. Which it will not be case, unless a metric depends on itself. 

I guess, that metrics, should be in fact the list regarding all the platform metrics (obtained with __platform.getMetricProviderManager().getMetricProviders()__). Still, after changing the list of possible metrics to those of all the platform, it only gets the dependencies of the first metric, but not the dependencies of the added ones.

Here is an example:
```
trans.sentiment
      |------->trans.codedetecting
                       |--------->trans.plaintext
````
The new transient metric for sentiments depends on the trans metric for code detection which in turn depends on the trans metric for plain text.

**Comment by creat89** [comment]
If the updating of the metrics dependencies are in fact necessary, I have a code that solves the problem. Including the update of the AnalysisTask.

**Comment by aabherve** [comment]
The splitIntoBranches function work as expected.

But we have identify and fix an issue in scava-admin web dashboard which could be the root cause of your issue : During Task creation and selection of the list of Metrics which will executed, we discovered an issue in the  selection algorithm which  select recursively  dependency of a selected metric.

**Comment by creat89** [comment]
Ok, I think I get it now. I was thinking that splitIntoBranches had to find the dependencies of the metrics in case the user did not declared them. But now I understand that splitIntoBranches check if the metrics that were declared to do are in fact dependencies of another metric, if so to set them in the correct branch.
