### ISSUE TITLE
ProjectAnalyzer not doing all the metrics

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#116]
Hello,

I have a weird problem with __ProjectAnalyzer__ and the method __filteredMetricProvider__. This a method that it is charged of converting the String that define a metric into a __IMetricProvider__. The problem is that not always the metrics are found. For example:

I have defined the following metrics for the analysis:
```
org.eclipse.scava.metricprovider.historic.bugs.emotions, 
org.eclipse.scava.metricprovider.trans.emotionclassification.EmotionClassificationTransMetricProvider, 
org.eclipse.scava.metricprovider.trans.bugs.emotions.EmotionsTransMetricProvider, 
org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider, 
org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider
```
However, the method __filteredMetricProvider__ only finds:
```
org.eclipse.scava.metricprovider.historic.bugs.emotions.EmotionsHistoricMetricProvider
```
If I just declare in the analysis:
```
org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider
```
Nothing is found.

However, if I debug and set a breakpoint in the loop that tries to find the match, everything is found. So, for the moment, my current patch is to add a `thread.sleep(500)` in __filterMetricProvider__. Which solves the problem for the moment.

Any ideas of why is this breaking and why do we need to pause the threads for skipping the problem?

**Comment by ambpro** [comment]
@creat89 , the most of the metric-providers given in this test case are not available on the `dev` branch. Could you tell me please which branch should I check out to reproduce the issue ?

**Comment by creat89** [comment]
Hello @ambpro, the branch is the [EHU_test_merge](/crossminer/scava/tree/EHU_test_merge). As well, in my last test, I'm having problems with the threading and the execution of multiple metrics at the same time despite their dependency. In order to run everyting correctly, I've been using the modified version of the ProjectAnalyzer.

**Comment by creat89** [comment]
Hello @ambpro, I have updated the branch, now it is [EHU_final](https://github.com/crossminer/scava/tree/EHU_final).

**Comment by ambpro** [comment]
Hi @creat89, I checked out the ` EHU_final` branch to reproduce the issue.
While debugging, I got a Delta creation failed due to an authentification problem related to the Github Session.
I guess it's the one specified in #129.
Do you have an workaround for that ?
`
No authentification data has ben set
Something went wrong during the creation of a Git Hub Session
ERROR [ProjectDelta (MeasurePlatform,20171001)] (11:14:34): Delta creation failed.
java.lang.NullPointerException
	at org.eclipse.scava.platform.bugtrackingsystem.github.GitHubManager.getAllIssues(GitHubManager.java:175)
	at org.eclipse.scava.platform.bugtrackingsystem.github.GitHubManager.getDelta(GitHubManager.java:92)
	at org.eclipse.scava.platform.bugtrackingsystem.github.GitHubManager.getDelta(GitHubManager.java:1)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:103)
	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by creat89** [comment]
Hello @ambpro,

I pushed a commit this morning on that branch that should solve the issue. Could you give a try or was it the last version of the branch the one with the issue?

**Comment by ambpro** [comment]
@creat89, It seems to be okey right now. Thank you :) 
I'll try to reproduce the original issue and provide you a feedback.

**Comment by ambpro** [comment]
Hi @creat89, I am not able to reproduce this issue even I used the `EHU_final` branch. Each time, the **filterMetricProvider** method return the metrics-providers inputs on both test cases.
You will find [application.log](https://github.com/crossminer/scava/files/2930961/application.log) logs file of the sample project.

**Comment by creat89** [comment]
Ok, I will check it again and for the moment I will close the issue. However, any news regarding issue #130 ? I see in the log that multiple plaintextprocessor  metrics for differents days are being called before the call of the codedetector. This might affect the data in the the transient metrics.
