### ISSUE TITLE
Propose backup, restore, or export, import features

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#119]
Administrators need to be able to backup their scava instance and restore it, both for production-grade hosting and for testing. What would be the steps required for that? Obviously there would the knowledge-base database to dump; but there are probably other files needed to restore an instance, like the API_GATEWAY parameter or maybe the data about currently analysed projects..
 
It doesn't need to be complex: a simple script to export/backup and import/restore an instance would suffice.

**Comment by borisbaldassari** [comment]
@mhow2 please feel free to add/comment. cheers!

**Comment by mhow2** [comment]
This issue relates to https://github.com/crossminer/scava-docs/issues/5
Developping a script is one thing, but for a start we would need the manual steps documented.

**Comment by borisbaldassari** [comment]
@aabherve during our last meeting we talked about a script or a procedure to backup/restore the db.. Could we use this issue to track progress on this? What you proposed seemed to fit well our (ow2's and eclipse's) needs..

**Comment by aabherve** [comment]
@borisbaldassari The scava-docs / installation guide has bean updated to include Backup qnd Restoration process for  the platform database
https://github.com/crossminer/scava-docs/blob/master/docs/installation-guide/database-backup.md

**Comment by borisbaldassari** [comment]
Looks good to me! thanks!
