### ISSUE TITLE
bugs.requests* metrics not working

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#120]
I have achieved the analysis on https://github.com/xwiki/xwiki-platform within ~ 1-month period (Jan/2 to Jan/31 2019)
The following metric shows zero values everywhere which is not consistent with the reality and notice as well that some days are missing.

The same looks to happen to every `bug.requests*` metrics

```json
{
  "id": "bugs.requestsreplies-useraverage",
  "name": "Comments, Requests and Replies Per User",
  "description": "The average number of comments, requests and replies per user, up to and including the current date.",
  "type": "LineChart",
  "datatable": [
    {
      "Date": "20190102",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190105",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190106",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190112",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190113",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190116",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190119",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190120",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190122",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190124",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190126",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190127",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    },
    {
      "Date": "20190128",
      "Comments": 0,
      "Requests": 0,
      "Replies": 0
    }
  ],
  "timeSeries": true,
  "ordinal": false,
  "x": "Date",
  "y": [
    "Comments",
    "Requests",
    "Replies"
  ]
}
```

**Comment by davidediruscio** [comment]
Hello @mhow2 do you have some logs to share for understand how to solve the issue?

**Comment by creat89** [comment]
Hello @mhow2,

I will check this with the new reader of GitHub and I will try to see what is going on.

**Comment by creat89** [comment]
Hello @mhow2,

Concerning the results of the metrics, all the values are zero because there are no issues in that project. They are only pull requests, which are not issues.

With respect to the days skipped, I couldn't reproduce this error. At least with the newest reader of GitHub this do not occur, and in MongoDB I can see 30 different entries. In all the cases, I don't think the reason of skipped days would be due to the metrics, but the MetricHistoricManager or similar, as the metric do not manage dates.

**Comment by mhow2** [comment]
>  Concerning the results of the metrics, all the values are zero because there are no issues in that project. They are only pull requests, which are not issues.

Indeed. This project use a standalone JIRA, I forgot about that. Now, I wonder how I can analyze JIRA issues because there still is no option in the Admin UI as of today.
