### ISSUE TITLE
register project : JIRA issue tracker as source

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#121]
Hello,
At the moment there is not way to analyze JIRA issues, or at least the option doesn't appear in the UI.
Could you inform when it is planned to add it ?

![2019-02-28_16-11](https://user-images.githubusercontent.com/9987241/53576244-87f88600-3b73-11e9-9e5a-6b39b5b0ee8c.png)

**Comment by creat89** [comment]
In the meantime, if you need to test other sources, you can use the code that I added in https://github.com/crossminer/EHU (private repository). If you have questions, just let me know.

**Comment by mhow2** [comment]
@creat89, @ambpro  : my use case is an end-user use case. How to use the code above , compile it is somehow outside of my UC scope. In addition I'm using the "official" docker stack so I should be able to add the source to a remote SCAVA instance.

What I tried to do is to add the following documents in Mongo (in `projects` collection  / `bugTrackingSystems` documents)


```json
{
    "_id" : "730ef697-de19-413f-af6a-2838d6dca0c7",
    "_type" : "org.eclipse.scava.repository.model.jira.JiraBugTrackingSystem",
    "persons" : [],
    "issues" : [],
    "_superTypes" : [ 
        "org.eclipse.scava.repository.model.jira.BugTrackingSystem"
    ],
    "url" : "https://jira.xwiki.org",
    "project" : "xwiki-platform",
    "_ossmeterId" : "xwiki/xwiki-platform:jira",
    "login" : "",
    "password" : ""
}

```

When I start the task again, I get : 
```
oss-app_1         | Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
oss-app_1         |     at com.mashape.unirest.request.BaseRequest.asBinary(BaseRequest.java:80)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.executeRestCall(JiraRestClient.java:181)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:166)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:156)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.getNextPage(JiraIssueIterator.java:50)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.hasNext(JiraIssueIterator.java:37)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.cacheItems(Cache.java:105)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.update(Cache.java:69)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.getItemsAfterDate(Cache.java:53)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:95)
oss-app_1         |     at org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:1)
oss-app_1         |     at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
oss-app_1         |     at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
oss-app_1         |     at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
oss-app_1         |     at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
oss-app_1         |     at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpUriRequest cannot be found by com.mashape.unirest_1.3.21
oss-app_1         |     at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
oss-app_1         |     at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
oss-app_1         |     at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
oss-app_1         |     at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
oss-app_1         |     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
oss-app_1         |     ... 19 more
oss-app_1         | Mar 18, 2019 12:18:25 PM org.restlet.engine.log.LogFilter afterHandle
```
In addition, I wonder if the login/password are required attributes ?

In the following method, it's not specified what is the `project` property ? Is it the JIRA project key or full name ?

https://github.com/crossminer/scava/blob/751cd654cb678a59d68c38fa8ef877a1eeec3933/metric-platform/platform-extensions/org.eclipse.scava.repository.model.jira/src/org/eclipse/scava/repository/model/jira/JiraBugTrackingSystem.java#L50 

I need clear statement/procedure how to add sources to project in the meantime we can do it from the API.

**Comment by creat89** [comment]
@mhow2: For adding a project from Jira, you can use the code that I posted before. There, you can find a method `createProjectWithBugTrackingSystemJira` for the object `ProjectCreationUtil`.

Concerning the error that you're seeing. This means that there is a dependency that it is not being loaded. In Eclipse go to Run/Run Configurations, then look for the name of the configuration that you're executing, such as scava.product, and then go to Plug-ins. There you'll need to add all the required plug-ins. Which in this case, it might be missing the apache one.

**Comment by mhow2** [comment]
Now I'm having this:
```
oss-app_1         | INFO  [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Starting Metric Execution (DAC_Java).
oss-app_1         | ERROR [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Exception thrown during metric provider execution (severityclassification).
oss-app_1         | java.lang.NullPointerException
oss-app_1         |     at org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider.prepareBugTrackerClassifierMessage(SeverityClassificationTransMetricProvider.java:376)
oss-app_1         |     at org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider.measure(SeverityClassificationTransMetricProvider.java:147)
oss-app_1         |     at org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider.measure(SeverityClassificationTransMetricProvider.java:1)
oss-app_1         |     at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | INFO  [AnalysisSchedulingService] (08:57:37): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider'
oss-app_1         | INFO  [AnalysisSchedulingService] (08:57:37): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider' is done.
oss-app_1         | INFO  [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Ending execution AnalysisTask 'XWikiwJIRA:all' with MetricExecution 'org.eclipse.scava.metricprovider.trans.severityclassification.SeverityClassificationTransMetricProvider' done in 71 ms
oss-app_1         | INFO  [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Starting execution AnalysisTask 'XWikiwJIRA:all' with MetricExecution 'trans.rascal.OO.java.CF-Java'
oss-app_1         | INFO  [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Adding dependencies to metricProvider 'trans.rascal.OO.java.CF-Java' into project 'XWikiwJIRA'
oss-app_1         | INFO  [MetricListExecutor (XWikiwJIRA, 20190318)] (08:57:37): Added dependencies to metricProvider 'trans.rascal.OO.java.CF-Java' into project 'XWikiwJIRA'
```

**Comment by creat89** [comment]
I'll check that issue as it concerns the severity classifier. However, it is possible that in EHU branch this has been solved, as some bugs have been found before.

**Comment by mhow2** [comment]
Thanks. Feel free to open a new issue if appropriate.

**Comment by creat89** [comment]
@mhow2, I think that the metric is breaking because the classifier cannot "find" the model. And it is not finding the model because it is zipped (too big for GitHub). In my branch, I updated some time ago that behavior, by creating a method that unzips a model if it is not found. As well, I found an issue with the Jira's reader (that happened before with Redmine) in which the messages are not stored.

**Comment by mhow2** [comment]
Thanks @creat89, I'm glad you found those issues. However, notice that at the moment we can't test your branch `EHU_final` because the CI build fails.

**Comment by creat89** [comment]
Yes, we know about that. Which it is a problem related to issue #133 and which I'm working on to solve it as soon as possible.

**Comment by creat89** [comment]
Well, I have merged EHU branch into the dev, so, now it should be able to analyze the projects with the new metrics. I have a doubt with the Severity classifier one, on my side it works perfectly, but I'm not sure if the build method it is going to like the approach that I used. Otherwise, I'll implement a new solution.

**Comment by creat89** [comment]
@mhow2 can we close this issue?

**Comment by mhow2** [comment]
I didn't have time to test. I got stopped by others bugs in the way ;)
Will test it by the end of the week.

**Comment by mhow2** [comment]
@creat89 if we stick to the original issue request, we are now able to configure a JIRA source when creating a new SCAVA project. However, @ambpro, it's not possible to edit the JIRA settings within the Admin UI afterwards. If it's known and still work in progress please close the issue.

**Comment by mhow2** [comment]
Please see #286 for admin frontend integration step.
