### ISSUE TITLE
[RESTMULE] Token using Basic Authentification GitHub

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#129]
Hello,

Currently the github reader based on restmule is not able to use a token for sessions as there is a problem in the authenfication. 

The method in `org.eclipse.scava.crossflow.restmule.client.github.session.GitHubSession`:
```
private GitHubSession(String token) {
		super(token);
	}
```
calls the method in `org.eclipse.scava.crossflow.restmule.core.session.AbstractSession`:
```
protected AbstractSession(@Nonnull String token) {
		setBasicAccessTokenInHeader(token);
		this.id = generateRandomId();
	}
```
which sets a session with a token in a header as basic authentification in:

```
protected void setBasicAccessTokenInHeader(@Nonnull final String token) {
		this.type = Auth.BASIC_AUTH;
		this.token = token;
	}
```
In the case of GitHub, at least, to send a token in header is not considered a basic authentification, but [OAUTH](https://developer.github.com/v3/#authentication).

In a previous and private copy of RESTMULE, I changed the `Auth.BASIC_AUTH` for `Auth.OAUTH`, which allows starting session correctly in GitHub using a token.

This issue is the same that I explained in crossminer/crossflow#1.

**Comment by patrickneubauer** [comment]
Hello,

Thank you for submitting this issue. 

Commit X should address it by replacing `Auth.BASIC_AUTH` with `Auth.OAUTH` for both `setBasicAccessTokenInHeader` as well as `setBasicAccessTokenInQuery`.

Cheers, Patrick
