### ISSUE TITLE
ProjectAnalyser problem with multi-day analysis

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#130]
Hello,

In the current version of the project analyzer I am seeing that multiple days (deltas) are being run at the same time. This seem to have a bad effect on the transient metrics which normally drop the collection at the end of the day. In other words, data is being lost due to this effect.

Here is an example (CodeDetectionMetric depends on TransPlainTextMetric):
_[Day1] TransPlainTextMetric: First drops the collection of trans metric in MongoDB. Analysis hundreds of messages.
[Day 2] TransPlainTextMetric: First drops the collection of trans metric in MongoDB. Analysis 0 messages.
[Day 2] TransCodeDetectionMetric: First drops the collection of trans metric in MongoDB. Analysis 0 messages.
[Day1] TransCodeDetectionMetric: First drops the collection of trans metric in MongoDB. Analysis less than 100 messages, as some were drop at Day 2 in PlainTextMetric._

Here is the [output](https://gist.github.com/creat89/a4ae3593de7012334e39cf17b87cd447) of the console from Scava. As you can see, the 15th Janaury, which was the first date ended the analysis almost at the end, while previous days were finished before. However, in the meantime the collection of transient metrics were dropped multiple times.

This bug might be related to issue #120, in which some days were missing in the analysis. There, the test I did was using a modified version of the ProjectAnalyser and that is why I couldn't reproduce the error.

**Comment by creat89** [comment]
Related to this issue, there are some transient metrics, specially those related to newsgroups, which cannot run on a multi-day analysis. The reason is that there are metrics based on threads, which cannot be built correctly if the analysis is not done sequentially.

**Comment by ambpro** [comment]
@creat89,
> In the current version of the project analyzer I am seeing that multiple days (deltas) are being run at the same time.

Currently, the project delta is created each day we execute the metric-providers.

Related to the metric-provider multiple days execution, I push a hotfixing for this issue. It's related a synchronize the Metric List execution inside the thread pool.
Could you please take a look on it ?

**Comment by creat89** [comment]
Yes, I'll check it and I'll tell you

**Comment by creat89** [comment]
With the hotfix everything seems to run correct.
