### ISSUE TITLE
virtual memory areas vm.max_map_count [65530] is too low in the elasticsearch container

### ISSUE THREAD

**Issue by davidediruscio** [crossminer/scava#141]
With the aim of documenting a step by step hello word scenario, now I'm not able to have the platform working on one VPS of mines I'm using for testing purposes. It seems that the elasticsearch container does not start because of the following error:

[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

This prevents the admin webapp to start and thus user is shown with the bad credential message.

@valeriocos is it possible to increase the vm.max_map_count value as suggested?

**Comment by valeriocos** [comment]
Yes, in the scava-deployment repo README there is a short explanation about how to do it:
https://github.com/crossminer/scava-deployment/tree/dev#issues

**Comment by borisbaldassari** [comment]
hi @davidediruscio you set me as an assignee, but I'm not sure what I can do.. how can I help on this one?

**Comment by davidediruscio** [comment]
Thanks @valeriocos
