### ISSUE TITLE
GitLab import : add issue tracker metadata

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#142]
We would need the issue tracker's `bugTrackingSystems` mongo object to be set with related data in the `projects` collection.

I suppose it would be needed by some partners, isn't @yannisKork , @creat89 ?

**Comment by creat89** [comment]
If I remember well, in EHU final branch I have pushed the modifications for the gitlab import reader to create automatically a gitlab issue tracker. But, I can't still build the branch using Jenkins. You can test it but you need to import the projects through Eclipse.

**Comment by mhow2** [comment]
> I have pushed the modifications for the gitlab import reader to create automatically a gitlab issue tracker

Thanks !

>  I can't still build the branch using Jenkins.

@tdegueul : are you able to help on this topic ?

**Comment by creat89** [comment]
@mhow2, @tdegueul is helping us to solve that problem, which right now it is issue #133.

**Comment by creat89** [comment]
@mhow2, this issue should be solved with the merge commit https://github.com/crossminer/scava/commit/b243dd5d0a48c1bc893a92a03d8c276f93dcc85c
