### ISSUE TITLE
SCAVA metricId didn't match with metricproviderId

### ISSUE THREAD

**Issue by ambpro** [crossminer/scava#160]
While I was working on the SCAVA data API refactoring discussed on #145, I found the following observations:
*  The Rest API exposed through `http://localhost:8182/analysis/metricproviders` retrieves the list of the metric providers loaded through the extension points mechnisms. Each metricprovider is identified with a `metricProviderId` field.
* The Rest API exposed through `http://localhost:8182/projects/p/<project-id>/m/<metric-id>` returns the list of the metrics with visualization. Its content refers to a fake json file, something like the following example:
```
{
	"metricid" : "org.eclipse.scava.metricprovider.historic.bugs.newusers",
	"vis" : [ 
		{
			"id" : "bugs.newUsers",
			"name" : "New Users",
			"description" : "The number of new users every day." ,
			"type" : "LineChart",
			"datatable" : {
				"cols" : [  { "name" : "Date", "field" : "$__date" }, 
					{ "name" : "Users", "field" : "$numberOfNewUsers" } ]
			},
			"x" : "Date",
			"y" : "Users",
			"timeSeries" : true
		},{
			"id" : "bugs.cumulativeNewUsers",
			"name" : "New Users (Cumulative)",
			"description" : "The number of new users up to and including the current date." ,
			"type" : "LineChart",
			"datatable" : {
				"cols" : [  { "name" : "Date", "field" : "$__date" }, 
					{ "name" : "Users", "field" : "$cumulativeNumberOfNewUsers" } ]
			},
			"x" : "Date",
			"y" : "Users",
			"timeSeries" : true
		}
	]

}
```
AFAIU, the metric with visualization identified by the `metricid` field could have one or multiple visualizations. Each visualization is identified by an `id` field.

The problem is that not all the `metricId` match with `metricproviderId` 
This the previous example the `metricId: org.eclipse.scava.metricprovider.historic.bugs.newusers` is not exist on the metricprovider provided on `http://localhost:8182/analysis/metricproviders`

If I call `http://localhost:8182/projects/p/QualityGuardAnalysis/m/bugs.cumulativeNewUsers`
The api returns an empty datatable filed as follow:
```
{
           "id": "bugs.cumulativeNewUsers",
           "projectId": "QualityGuardAnalysis",
           "metricId": "org.eclipse.scava.metricprovider.historic.bugs.newusers",
           "name": "New Users (Cumulative)",
           "description": "The number of new users up to and including the current date.",
           "type": "LineChart",
           "datatable": [],
           "timeSeries": true,
           "ordinal": false,
           "x": "Date",
           "y": "Users"
}
```
Otherwise, the project database contains all the analysis data
![QualityGuard](https://user-images.githubusercontent.com/35226648/55494991-33e23500-563c-11e9-8923-8165bc81ee6e.png)

I guess it has a relation with the issue #139

**Comment by tdegueul** [comment]
Very good catch. @valeriocos @mhow2 @borisbaldassari can you check whether this helps with #139?

**Comment by borisbaldassari** [comment]
@tdegueul Not sure how I can check, but it makes a lot of sense at the very least. 
I'm indeed using the "viz" metrics to fetch everything automatically for the project. So that could explain why I get zero metrics e.g. from sirius on ci4.
If there is anything I cna test/try further please let me know..

**Comment by valeriocos** [comment]
@tdegueul same comment as @borisbaldassari . I'll wait for the fix and check if new data is available when querying the scava api endpoints.

**Comment by mhow2** [comment]
`bugs.cumulativeNewUsers`'s datatable looks ok on my side currently. What about this issue @ambpro ?

**Comment by ambpro** [comment]
the commit https://github.com/crossminer/scava/commit/f221683f24d9fc99e4ae2f9a97093d8042a1e17b should fix this issue, I close it !
