### ISSUE TITLE
Add recommendation feedback

### ISSUE THREAD

**Issue by md2manoppello** [crossminer/scava#163]

**Comment by md2manoppello** [comment]
@geryxyz

**Comment by md2manoppello** [comment]
Data model is stored at https://github.com/crossminer/scava/blob/16de4e25ecee298c45a80949074e54723bcb6f17/knowledge-base/org.eclipse.scava.knowledgebase/src/main/java/org/eclipse/scava/business/dto/RecommendationFeedback.java#L1

**Comment by geryxyz** [comment]
@Szamos96 @idarav please check this.
