### ISSUE TITLE
unable to edit existing task

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#172]
in the latest build (150), I am unable to edit an existing task. I get an error 500 from the MP's logs instead then the task vanish.

[Download and see the video](https://nextcloud.ow2.org/index.php/s/HYFR8ZxkQCbYQmP/download) to get how to reproduce.

Logs:
[scava-deployment_oss-app_1-2019-04-15@11:17.log](https://github.com/crossminer/scava/files/3079834/scava-deployment_oss-app_1-2019-04-15%4011.17.log)
[metric-pf.log](https://github.com/crossminer/scava/files/3079835/metric-pf.log)

**Comment by mhow2** [comment]
thanks Amin, it seems to work. Can you please tell how you find out where the problem was before closing ?

**Comment by ambpro** [comment]
Actually, the issue was due to the scava apis refactoring on https://github.com/crossminer/scava/issues/145#issuecomment-472918034.

**Comment by ambpro** [comment]
Btw, I wasn't able to reproduce the same log's issue on dev environnement. In my side, I had `nullPointerException`.

**Comment by mhow2** [comment]
>  In my side, I had `nullPointerException`.

We have this too, in the log attached above

**Comment by ambpro** [comment]
Hi @mhow2, does the commit https://github.com/crossminer/scava/commit/1586b551d968733d7fe7fc293e69a27d4f0508ec fix the isssue?

**Comment by mhow2** [comment]
> Hi @mhow2, if the commit [1586b55](https://github.com/crossminer/scava/commit/1586b551d968733d7fe7fc293e69a27d4f0508ec) fix the issue, we can close it !?

it is.
