### ISSUE TITLE
org.eclipse.scava.metricprovider.trans.rascal.bugheadermetadata

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#174]
Hello,

Today I pushed an commit and at first sight I though that I modified a file from you without knowing. In Scava there is a folder called `org.eclipse.scava.metricprovider.trans.rascal.bugheadermetadata`, however, the project is called `org.eclipse.scava.metricprovider.trans.bugs.bugmetadata`. Do you know, which should be the correct name either of the folder or the project? I don't think it has to do anything with rascal, tbh.

**Comment by tdegueul** [comment]
You can go ahead and remove Rascal from the name, indeed. Don't forget to update https://github.com/crossminer/scava/blob/dev/metric-platform/pom.xml accordingly!
