### ISSUE TITLE
Add projects and tasks from Eclipse for debugging

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#177]
Today I'm getting a `java.lang.NullPointerException` in MetricVisualisationExtensionPointManager, more specifically in line 59:
`IExtensionPoint extensionPoint = Platform.getExtensionRegistry().getExtensionPoint(extensionPointId);`

The reason is that Platform.getExtensionRegistry() is returning null and, in consequence, everything is breaking.

The error happens when I try to call `createAnalysisTask(String projectId, AnalysisTask task, List<String> metricsProviders)` using a code that I've been using for a while for adding projects using code instead the UI.

The error happens with the first metricProvider that I have declared: `org.eclipse.scava.metricprovider.trans.plaintextprocessing.PlainTextProcessingTransMetricProvider`

By catching the null value and returning and empty `visMap`, I can run everything as normal.

**Comment by tdegueul** [comment]
Hey @creat89. In which context do you run your code? `Platform.getExtensionRegistry()` will always return `null` unless you're calling it in the context of an Eclipse application, i.e., you cannot call this from your own `main()`. Do you observe this behavior when running the full Scava platform?

**Comment by creat89** [comment]
The code that I'm using is similar to the one that was used in Ossmeter to insert projects in the database. In fact, it's only a modified version that now includes elements that are related to the selection of metrics and dates of the analysis. Until not long ago, I could use it without any problems. You can check the code (it might have changed a bit) in https://github.com/crossminer/EHU

Let me know what do you think.

**Comment by tdegueul** [comment]
It seems that the code you're invoking in `AnalysisTaskService` is Eclipse-dependent (it accesses the platform, bundles, etc.). It is weird to me that you were ever able to make your code work, unless `AnalysisTaskService` wasn't Eclipse-dependent before.

I do not see any easy solution. You should make sure to invoke your code from an Eclipse context to make it work. If you want to create projects manually, you can try to do it from an Eclipse plug-in test, as is the case for instance in https://github.com/crossminer/scava/blob/dev/metric-platform/tests/org.eclipse.scava.platform.tests/src/org/eclipse/scava/platform/tests/RunMetricsTest.java. Or you could try to make an API call to `:8182`.

Let me know if it helps.

**Comment by creat89** [comment]
OK, I'll check the proposed solutions. In all the cases, I will at a certain point to install the docker image in our server. But, that method is always harder to debug.

**Comment by tdegueul** [comment]
Indeed this is painful. You can have a look [here](https://github.com/crossminer/scava/blob/dev/metric-platform/tests/org.eclipse.scava.platform.tests/src/org/eclipse/scava/platform/tests/ProjectAnalysisTests.java) for more inspiration. These tests directly interact with the rest API to import project, create and run tasks, etc. And they are tests so you can easily run them from Eclipse.

**Comment by creat89** [comment]
Thank you, I'll check that too.

**Comment by creat89** [comment]
By the way, I guess that the `AnalysisTaskService` wasn't before Eclipse dependent, as part of my code (the one that adds the task) comes from the code found here: 

https://github.com/crossminer/scava/tree/dev/metric-platform/platform/org.eclipse.scava.platform/src/org/eclipse/scava/platform/analysis/tests

That's how I determined how to add and activate the tasks using external code.
