### ISSUE TITLE
delete project : matching database is not dropped

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#179]
I just observed this which incidentally led to #178 while working with @creat89.
When you delete a project from the UI, it looks like it worked (gone) but if you look at mongo the db is still there.
The software doesn't provide any interesting logs entry to show when doing so.

**Comment by mhow2** [comment]
A bit more of info about this issue. Taking the project https://github.com/KnowageLabs/Knowage-Server and reproducing #181 , I get the two dbs `Knowage-Server` and `KnowageServer`.

When I delete this project from the UI, it seems KnowageServer is dropped but not `Knowage-Server`

**Comment by tdegueul** [comment]
b5505d484b11fbfbe9f9e1c0c131954acc4ddc4c should help?

**Comment by mhow2** [comment]
> [b5505d4](https://github.com/crossminer/scava/commit/b5505d484b11fbfbe9f9e1c0c131954acc4ddc4c) should help?

Doesn't seem to. I still see that for project https://github.com/docdoku/docdoku-plm the database is not dropped when the project is effectively deleted from the UI/API.

Step to reproduce:
- import https://github.com/docdoku/docdoku-plm
- create and start a task wait for it to begin (so the db is created)
- stop the task
- delete the project
At this point you should still see the `docdokuplm` db

**Comment by mhow2** [comment]
FYI @ambpro , @tdegueul it is still broken. I am able to reproduce. However, it seems to work with https://github.com/INRIA/spoon so I don't understand what is going on.

**Comment by tdegueul** [comment]
We had issues with special character in project names so I pushed b5505d484b11fbfbe9f9e1c0c131954acc4ddc4c to unify them. The part of the code that takes care of removing the databases probably does not use `shortName` but something else. @ambpro @aabherve any idea where is the code that deletes the DBs to make sure it uses the `shortName` convention?

**Comment by ambpro** [comment]
@tdegueul, the code responsible to remove the projects DBs is [here](https://github.com/crossminer/scava/blob/dev/metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ProjectDeleteResource.java#L62).

**Comment by tdegueul** [comment]
Thanks @ambpro! #238 should solve the problem then, right? If it looks good to you, please merge! Let us know how it goes @mhow2!

**Comment by ambpro** [comment]
Thank you @tdegueul for the fix, it works fine right now. @mhow2, I am able to drop both the https://github.com/KnowageLabs/Knowage-Server and https://github.com/docdoku/docdoku-plm projects.

**Comment by mhow2** [comment]
Thanks. It seems to work, closing !
