### ISSUE TITLE
collections for a single project spreaded over two dbs

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#181]
In this example, I have a task to run over the project https://github.com/KnowageLabs/Knowage-Server

I selected a few metrics about commits (5 of them):

![2019-04-19_09-37](https://user-images.githubusercontent.com/9987241/56413165-d5959300-6286-11e9-900d-abcb0fd8d1f4.png)

now, when I look at mongo I get two dbs with collections in there.
I also notice that `rascal.generic.churn.filesPerCommit.historic` is in both databases, and the one in `Knowage-Server` is empty

```
> use Knowage-Server;
switched to db Knowage-Server
> show collections;
rascal.generic.churn.filesPerCommit.historic
> db.rascal.generic.churn.filesPerCommit.historic.find()
(nothing)
```

```
> use KnowageServer;
switched to db KnowageServer
> show collections;
Commits.commits
Commits.repositories
factoids
historic.commitsovertime.CommitsOverTimeHistoricMetricProvider
rascal.generic.churn.filesPerCommit
rascal.generic.churn.filesPerCommit.historic
```

I am also suprised to get only one metric result available from the API (`/metrics/p/KnowageServer`)

```json
[
  {
    "id": "commitsovertimeline",
    "projectId": "KnowageServer",
    "metricId": "org.eclipse.scava.metricprovider.historic.commitsovertime.CommitsOverTimeHistoricMetricProvider",
    "name": "commits",
    "description": "This metric shows a cumulative count of the commits.",
    "type": "LineChart"
  }
]
```

wdyt @tdegueul ?

**Comment by tdegueul** [comment]
Yup, this is a known bug imported from OSSMETER.

I encountered another bug today which simply breaks _everything_ when a project's name contains a `.` (the case for instance for https://projects.eclipse.org/projects/tools.cdt).

I would suggest to simply post-process project's names and shortNames to remove every special character (`-`, `_`, `.` and the like). The downside would be that projects `ab`, `a-b` and `a.b` would collide.

@ambpro would you be fine if I push a fix for that?

**Comment by ambpro** [comment]
@tdegueul , please feel free to go ahead in order to fix that! thank you :)

**Comment by tdegueul** [comment]
b5505d484b11fbfbe9f9e1c0c131954acc4ddc4c should help.

**Comment by mhow2** [comment]
looks fixed
