### ISSUE TITLE
Display platform exceptions in the admin UI

### ISSUE THREAD

**Issue by tdegueul** [crossminer/scava#182]
Exceptions raised when executing metrics are stored in a collection `errors` in the `scava` database (see the DB model in `org.eclipse.scava.repository.model.ProjectError`, which notably contains the stacktrace).

It would be extremely helpful to display these errors/stracktraces somewhere in the admin UI to ease debugging. Something as simple as a list of errors with the associated project and stacktrace.

**Comment by tdegueul** [comment]
Copying error logs from `OssmeterLogger` to this `errors` collection might be helpful too. Currently, only exceptions raised by (Rascal?) metric providers are stored there. Logging every error encountered by the platform in the collection would be best.

**Comment by ambpro** [comment]
Closing the ticket !
