### ISSUE TITLE
register project : mbox/sympa as source

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#189]
Hi @crossminer/ehu 
In order to test NLP against mailing lists, we still need a way to include an mbox/sympa archive into the platform through the admin UI / REST API as discussed some weeks ago.
It is possible that @borisbaldassari is expecting it too.

**Comment by mhow2** [comment]
Waiting for a merge in "dev" so I can test.

**Comment by Danny2097** [comment]
@mhow2 I am currently working on resolving some merge conflicts before I can merge to the `dev` branch. I will update you as soon as this has been completed.

**Comment by Danny2097** [comment]
Hi @mhow2 @ambpro,
We recently merged the `EHUforums` branch in to the `dev` branch. As a result the *Sympa* reader is now available within the platform and now requires the ability to register a Sympa project via the UI.

I have provided details below regarding the current project parameters:

The following are *Mandatory*:

- `MAILINGLISTNAME`= _Name of the mailing List_
- `MAILINGLISTDESCRIPTION` = _description of the mailing list_
- `COMPRESSEDFILEEXTENSION`  = _file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)_

The following parameters are *optional* (if the location of the archive is protected by basic authentication)

- `USERNAME` = _username_
- `PASSWORD` = _password_


Also, @yannisKork  recently completed the parser for the Mboxes and the reader is currently in development by @nnamokon.

**Comment by nnamokon** [comment]
Hi @mhow2 @ambpro,
The Mbox reader is now available within the platform and now requires the ability to register a project via the UI. I have provided details below regarding the current project parameters:
Mandatory parameters:
MBOXNAME= Name of the Mbox
MBOXDESCRIPTION = description of the Mbox
COMPRESSEDFILEEXTENSION = file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)
Optional parameters (if the location of the archive is protected by basic authentication):
USERNAME = username
PASSWORD = password

**Comment by ambpro** [comment]
Hello @Danny2097 @nnamokon,

> COMPRESSEDFILEEXTENSION = file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)

> COMPRESSEDFILEEXTENSION = _file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)

Could you please explain with more details the nature of the COMPRESSEDFILEEXTENSION field?
From the `sympa` and `mbox` data models they should be a string !?

**Comment by creat89** [comment]
@ambpro, yes it should be a string. Currently, the values of that string can be either (.tar.gz) or (.tgz).

**Comment by ambpro** [comment]
Hello all,
the commit https://github.com/crossminer/scava/commit/5cf097f8509a0602bbca3d4ec51eeac8006ea0b9 should add a support for both mbox/sympa sources.

**Comment by nnamokon** [comment]
Hi @ambpro ,
Minor correction - URL is required to register Mbox project as well.
