### ISSUE TITLE
BitBucket Reader Too Many Parameters

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#190]
While checking the bitbucket reader on the UI, I noticed that the reader asks for multiple elements that are redundant. More specifically, it asks for `URL`, `Owner` and `Repository`. These two last elements can be obtained from the `URL`. While the element `User` do not seem to have a particular use.

To simplify the elements necessary to fill while adding a BitBucket project in the UI, I have asked in issue https://github.com/crossminer/scava/issues/175, to remove elements such as `Owner`, `Repository` and `User`. Thus, a change in the way the BitBucket reader should be done.

**Comment by creat89** [comment]
In commit https://github.com/crossminer/scava/commit/1bb6a48f22edb647371d2a5775580d1f7930561a, I have included a method that parses the URL of a BitBucket project. It obtains the host (which now can be different than bitbucket.org), the repository owner and the repository.

However, it still contains multiple parameters that are no longer needed. These will have to be deleted once the code related to the creation of a project (https://github.com/crossminer/scava/issues/175) will be modified.

**Comment by Danny2097** [comment]
I have trimmed the Bitbucket model removing all necessary parameters.  I will push these changes once we have confirmation that changes have been implemented in issue #175 to prevent / avoid errors.
