### ISSUE TITLE
BitBucket Reader and Former users

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#191]
BitBucket reader will break if the creator of an issue (and I guess of a comment too) is Null.

The creator of an issue is going to be Null when it is no longer a user from BitBucket. 

A reproducible example is:

https://bitbucket.org/fenics-project/dolfin/issues/7

https://api.bitbucket.org/2.0/repositories/fenics-project/dolfin/issues/7

The object returned by the reader has a null in the reporter, which it is used for populate the field creator.

**Comment by Danny2097** [comment]
This has been addressed in https://github.com/crossminer/scava/commit/c5c765f6b3b68728fa0eed015859e66f8037c26b

Essentially the Bitbucket manager now will check for these instances in both issues and comments. If null is detected, the creator field will be populated with the String "Former User"
