### ISSUE TITLE
Mantis BT Reader asking for redundant parameters

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#194]
Currently for Mantis BT, it is necessary to indicate Token, URL, host and ProjectID. The last two elements can be obtained from the URL.

**Comment by creat89** [comment]
@Danny2097, for solving this issue you can use the code that I implemented for BitBucket, which from the URL of a project it determines the host and project id.

**Comment by creat89** [comment]
@Danny2097 the fix to this issue has to be posted once issue #175 has been modified to avoid conflicts in the code.

**Comment by Danny2097** [comment]
I have removed all the unnecessary project parameters and will push once we have confirmation that issue #175 has been addressed.

**Comment by Danny2097** [comment]
To summarise, I removed the `host` parameter, refactor `project_id` to `project_identifier`.
refactored the reader to reflect the changes to the repo model and also removed unused dependencies.
