### ISSUE TITLE
Mantis BT Reader might keep in memory multiple issues from previous dates

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#195]
Checking the code of Mantis BT Manager, I have noticed that the list that stores the issues is initialized when the Mantis BT Manager is created. This means that one object will store all the information regarding issues from all the projects analyzed with Mantis BT.

Moreover, the list is never emptied, thus it will store the issues of days already analyzed by the platform.

I think that the list should be created during the call of `getDelta` or at least clean every time this method is going to end.

**Comment by Danny2097** [comment]
This issue has been fixed in https://github.com/crossminer/scava/commit/311df73cfc7239779f66ba1db9d94d5f9fd0db2b
