### ISSUE TITLE
Puppet: viz metrics id, name, description naming

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#201]
Hello @crossminer/aueb.
Here is a metric viz as exposed by the rest API:

```
  {
    "id": "designsmells.brokenSmells",
    "name": "Broken Hierarchy Smells",
    "description": "The number of Broken Hierarchy smells per day, up to and including the current date.",
    "type": "LineChart",
    "datatable": {
      "cols": [
        {
          "name": "Date",
          "field": "$__date"
        },
        {
          "name": "Smells",
          "field": "$numberOfBrokenSmells"
        }
      ]
    },
    "x": "Date",
    "y": "BrokenHierarchySmells",
    "timeSeries": true,
    "metricId": "org.eclipse.scava.metricprovider.historic.configuration.puppet.designsmells.PuppetDesignHistoricMetricProvider"
  },
```

 I noticed that the `id`, `name` and `description` fields in the viz metrics exposed at `/metrics` related to Puppet don't contain any mention to "puppet". For instance I believed until to today that those metrics could apply to JAVA code until I had a look at the `metricId` field, and see `puppet` in `org.eclipse.scava.metricprovider.historic.configuration.puppet.designsmells.PuppetDesignHistoricMetricProvider`

To avoid confusion, It would be great for Web apps that are using the REST API to have the information in those three fields:

id|Name|Description
--|--|--
designsmells.brokenSmells | Broken Hierarchy Smells | The number of Broken Hierarchy smells per day, up to and including the current date.
designsmells.deficientSmells | Deficient Encapsulation Smells | The number of Deficient Encapsulation smells per day, up to and including the current date.
designsmells.hairballSmells | Hairball Structure Smells | The number of Hairball Structure smells per day, up to and including the current date.
designsmells.imperativeSmells | Imperative Abstraction Smells | The number of Imperative Abstraction smells per day, up to and including the current date.
designsmells.insufficientSmells | Insufficient Modularization Smells | The number of Insufficient Modularization smells per day, up to and including the current date.
designsmells.missAbSmells | Missing Abstraction Smells | The number of Missing Abstraction smells per day, up to and including the current date.
designsmells.missingDepSmells | Missing Dependency Smells | The number of Missing Dependency smells per day, up to and including the current date.
designsmells.multifacetedSmells | Multifaceted Abstraction Smells | The number of Multifaceted Abstraction smells per day, up to and including the current date.
designsmells.smells | Sum of Design Smells | The number of design smells per day, up to and including the current date.
designsmells.tightSmells | Tightly-coupled Module Smells | The number of Tightly-coupled Module smells per day, up to and including the current date.
designsmells.unnecessarySmells | Unnecessary Abstraction Smells | The number of Unnecessary Abstraction smells per day, up to and including the current date.
designsmells.unstructuredSmells | Unstructured Module Smells | The number of Unstructured Module smells per day, up to and including the current date.
designsmells.weakenSmells | Weaken Modularity Smells | The number of Weaken Modularity smells per day, up to and including the current date.

**Comment by blueoly** [comment]
Hello @mhow2 . To clarify your suggestion, do you mean that it would be better if we add the word "Puppet" in these three fields?

**Comment by mhow2** [comment]
> Hello @mhow2 . To clarify your suggestion, do you mean that it would be better if we add the word "Puppet" in these three fields?

In short yes. For others metrics like `newsgroup.*` or` bugs.*` it's already straighforward.
What I mean overall is that the user that develops on the top of the REST API viz metrics (`/metrics`) should clearly understand by the response, to **which kind** of metric he's facing. In fact even the end user should be aware :  Is it about source code ? communication channels ? One can of course take a look at `metricId`, but I find the string `org.eclipse.scava.metricprovider.historic.configuration.puppet.designsmells.PuppetDesignHistoricMetricProvider` a bit long...

The same observation apply when retrieving values for a specific metric with : `/projects/p/spoon/m/designsmells.brokenSmells`

Or if not mentioned is id/name/description, there could be a field that provide the **nature** of what being analyzed :  for example : "puppet", "sourcecode_java", "sourcecode_agnostic", "bugtracker_comment", "commits". Those are arbitrary example of what I have in mind just to show what I have in mind.

wdyt on your side @ambpro , @tdegueul ?

**Comment by blueoly** [comment]
I see your point and I agree. I will align my naming conventions with the other metrics, like bugs.* metrics. I am in the process of adding the final version of puppet metrics and the first version of Docker metric until tomorrow, so your suggestion was right on time. Thank you and please have a look on our metrics when we add the metrics.

**Comment by blueoly** [comment]
Hi @mhow2 . I have merged the changes that correspond to your suggestions to the dev branch, so you can check if now the info provided from our metrics are self-explanatory enough and if they are, we can close this issue.

**Comment by mhow2** [comment]
LGTM !
