### ISSUE TITLE
WorkingCopyFactory returning last version of file

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#210]
Hello,

I'm working on retrieving files posted on a GitHub Wiki (which are stored as git projects) using a vcs reader. While using `WorkingCopyFactory` for getting the different versions of a GitHub Wiki, I've noticed that it is returning me the last version of the file, instead of the one asked by the revision hash.

For example, I'm analyzing `https://github.com/creat89/SummTriver.wiki.git`, the first revision is on 15/01/2019 with `https://github.com/creat89/SummTriver/wiki/Home/2e8c6e6b6e8a4c7a5fa526ec18ac9116e7c0112b` and instead of getting that version of the Home.md file, when opening the file I'm getting the version of the last commit `https://github.com/creat89/SummTriver/wiki/Home/040ec4810285f424adba7d938f13f0a1015af155`.

![image](https://user-images.githubusercontent.com/17121539/57657756-39845080-75d4-11e9-9e95-5732a5d83442.png)

**Comment by blueoly** [comment]
Hi @creat89. I am also using WorkingCopyFactory to retrieve the different revisions of a repository and it is working fine. I guess that you are not checking out the correct revision based on the deltas, so you are just getting the version of the last commit. Have a look in the following file, it may help you.

https://github.com/crossminer/scava/blob/dev/metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.configuration.docker.smells/src/org/eclipse/scava/metricprovider/trans/configuration/docker/smells/DockerTransMetricProvider.java

It would help if you point us to your code to get a better understanding of the situation.

**Comment by creat89** [comment]
Hello @blueoly, yes, in fact I learnt how to have access to the files checking your code.

I'm using the following approach:

https://github.com/crossminer/scava/blob/dev/metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.documentation/src/org/eclipse/scava/metricprovider/trans/documentation/DocumentationTransMetricProvider.java

As you can see the commit reference in getting it from the delta.

**Comment by blueoly** [comment]
It is strange because it seems that you are doing it correctly, unless I am missing something. I hope that @tdegueul will be able to find what I am missing.

By the way, are you sure that you need to do all these iterations in your code? I think that you have to consider only the revision of the last commit for each delta, as we essentially store only one value for each delta/day to mongodb.

**Comment by creat89** [comment]
Unless I'm wrong, I have that amount of iteration because I'm considering the fact that in one day, we can push multiple commits that modify different files. So for a specific day, in commit 1, I may have created Home.md and in commit 2, I created Citation.md. By just reading the last commit,, I'm missing the first file, isn't?

**Comment by blueoly** [comment]
By checking out the last revision of the day, the working folder will contain both files, so I think that you will not miss anything.

**Comment by creat89** [comment]
Yes, I see that point. That's useful if we need to analyze all the files in the repository always. But if I need to analyze only those modified in the commits, I need to read commit by commit and get the name of the modified file. Although I can ask only for the files of the last commit of the day, and then filter them according to the modified files.

**Comment by blueoly** [comment]
It seems it is relevant to the nature of each metric provider. So, in your specific case, you may have to keep the iterations.
