### ISSUE TITLE
Inform users of limitations and configuration modifications relating to MantisBT

### ISSUE THREAD

**Issue by Danny2097** [crossminer/scava#212]
An instance of Mantis BT in it's default configuration does not return `closed` issues when a request is made via the REST API ([See this forum post here](https://www.mantisbt.org/forums/viewtopic.php?f=3&t=20599&p=54037&hilit=issues+does+not+closed#p54037)).

 In order for this reader to function correctly (and to analyse all issues regardless of their state) the administrator is required to modify or a add the parameter `$g_hide_status_default  = META_FILTER_NONE;` located in `.../config/config_inc.php`  in order for the REST API to also include closed issues in the `getIssues` request.

It would be nice to see some kind of functionality in the front end of CROSSMINER which informs users of a potential limitation and solution when choosing to analyse a project hosted in a Mantis BT instance. As without this modification the metrics produced will not be representative of the actual projects state.

**Comment by creat89** [comment]
Hello @nnamokon,

I think that this limitation and configuration aspect would go perfectly in the readers documentation. Could you update the documents?

**Comment by Danny2097** [comment]
@nnamokon has this issue been addressed? If it has please can you close it.

**Comment by nnamokon** [comment]
@Danny2097 I have added this to the documentation.
