### ISSUE TITLE
Commit  8e6a3d5e merge issues

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#213]
Hello @blueoly and all developers,

Commit https://github.com/crossminer/scava/commit/8e6a3d5ee71f8b0d8e2d0b5d0049f114196217ff  when solving some merge problems added some projects that have been removed from the platform for a time. I have found two projects related to us that should not appear anymore, I'll try to remove them in the next commit.

**Comment by creat89** [comment]
This projects were added, however, the content only consisted on the .project file. Please check your repositories.
- https://github.com/crossminer/scava/tree/dev/metric-platform/metric-providers/org.eclipse.scava.requestreplyclassifier.opennlptartarus.libsvm
- https://github.com/crossminer/scava/tree/dev/metric-platform/metric-providers/org.eclipse.scava.sentimentclassifier.opennlptartarus.libsvm
- https://github.com/crossminer/scava/tree/dev/metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.threads
- https://github.com/crossminer/scava/tree/dev/metric-platform/metric-providers/org.eclipse.scava.metricprovider.trans.rascal.bugheadermetadata

**Comment by blueoly** [comment]
My apologies. When I tried to resolve the conflicts in the feature.xml, all of the file was shown as conflict because at the end of every line there was a special character added (maybe a Windows special character) and I couldn't resolve properly the conflicts as it seems from the result.

**Comment by creat89** [comment]
I think it is solved now, I'll close the issue.
