### ISSUE TITLE
Commit Problem

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#221]
Hello,

One commit removed several elements that make my local version to do not work anymore. Among the elements the removed that I can see is that all the new tools developed on NLP are not anymore linked to the features.xml.

For example, you cannot find anymore the features with NLP, such as org.eclipse.scava.nlp.classifiers.sentimentanalyzer:

https://github.com/crossminer/scava/blob/dev/metric-platform/platform/org.eclipse.scava.platform.feature/feature.xml

While here:

https://github.com/crossminer/scava/blob/7655050250c376ec663a8b59f3cf53bfe58f5139/metric-platform/platform/org.eclipse.scava.platform.feature/feature.xml

You can find that element. 

I don't know how to solve all.

**Comment by creat89** [comment]
I have other examples. From this:

https://github.com/crossminer/scava/blob/da490b86a30747bb61b0317d8d7e292058fedaee/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github/META-INF/MANIFEST.MF

To this:

https://github.com/crossminer/scava/blob/dev/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github/META-INF/MANIFEST.MF

How can that happen?????

**Comment by blueoly** [comment]
Hi @creat89 . The commit that you posted was mine. But this commit was made in order to re-add the metric providers that I have implemented that were removed by this commit (1b773e9).

**Comment by creat89** [comment]
@blueoly, I don't think it was you or only you. Look in https://github.com/crossminer/scava/commits/dev/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github/META-INF/MANIFEST.MF
I don't see your username commiting on that file.

**Comment by davidediruscio** [comment]
Hi Adrian

I guess this is due to the last commit about the new target definition. @tdegueul , @ambpro Am I wrong? could you please have a look?

Thanks
Davide

**Comment by creat89** [comment]
Hello @davidediruscio,

We were discussing this issue yesterday on Slack, they are checking the issue.

**Comment by blueoly** [comment]
Hi Davide,

we had a short discussion with Thomas in Slack yesterday afternoon and the problem is indeed the merge of the target-definition. They are checking it.
