### ISSUE TITLE
strange result with bugs.unansweredBugs

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#246]
Still on the good old https://github.com/docdoku/docdoku-plm project

In the following result provided by the platform, I got the feeling there is something wrong as the value suddenly going from zero to 65 on 20180316.

Could you have a look ? 

```json
{
  "id": "bugs.unansweredBugs",
  "projectId": "docdokuplm",
  "metricId": "org.eclipse.scava.metricprovider.historic.bugs.unansweredbugs.UnansweredThreadsHistoricMetricProvider",
  "name": "Unanswered Bugs",
  "description": "The number of unanswered bugs per day, up to and including the current date.",
  "type": "LineChart",
  "datatable": [
    {
      "Date": "20180101",
      "Bugs": 0
    },
    {
      "Date": "20180102",
      "Bugs": 0
    },
(...zero value until...)
    {
      "Date": "20180316",
      "Bugs": 65
    },
    {
      "Date": "20180317",
      "Bugs": 65
    },
```

**Comment by creat89** [comment]
Hello @mhow2,

Believe it or not, a miracle happened the 16/03/2018 on docdoku-plm project: A github user woke up with the goal of replying, updating, even closing very old issues. 🤣

Here are some examples:
- [871](https://github.com/docdoku/docdoku-plm/issues/871)
- [838](https://github.com/docdoku/docdoku-plm/issues/838)
- [873](https://github.com/docdoku/docdoku-plm/issues/873)
- [885](https://github.com/docdoku/docdoku-plm/issues/885)
- [722](https://github.com/docdoku/docdoku-plm/issues/722)

Some other issues, were just updates in the labels:
- [391](https://github.com/docdoku/docdoku-plm/issues/391)

So, yes, the outcome of the metric is the correct one.
