### ISSUE TITLE
review viz metric description and names

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#247]
We need to make the metrics name and description - which are available from the REST API then displayed in the dashboards and so - to be as clear as possible.  For instance, for `bugs.bugs` currently has `The number of bugs per day, up to and including the current date.` when in fact it could be more consistent with `The number of bugs per day that have been updated, commented or submitted up to and including the current date.`

Also, sometimes,the name is wrong : for example the name for `bugs.averageResponseTime` is `Average Response Time (ms)` . it should be `seconds` instead of `ms`

**Comment by mhow2** [comment]
Hi @nnamokon please could you report on this ?
I'm also concerned (as discussed with @valeriocos and in issue https://github.com/Bitergia/prosoul/issues/110) with some metric that have the same exact `name` value. We have to remember that the metric name is the string which is used in dashboards or prosoul to as labels. So to me the name should be unique and accurate enough to what it applies.

For example we currently have (it is only an except):

id|name
-- | --
bugs.activeusers | Active Users
newsgroups.activeusers | Active Users
bugs.activeusers | Active Users
bugs.averageResponseTime | Average Response Time (ms)
newsgroups.averageResponseTime | Average Response Time (ms)
bugs.averageResponseTime | Average Response Time (ms)

**Comment by nnamokon** [comment]
Hi @mhow2 and @valeriocos,
All the metric <names> are now unique and reflect the information being passed.

**Comment by valeriocos** [comment]
Thank you @nnamokon for the info.

**Comment by mhow2** [comment]
Thanks !
