### ISSUE TITLE
dealing with zero values in viz metrics (especially duration-related ones)

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#248]
as discussed with @creat89 and @valeriocos, `bugs.averageResponseTime` (among other metrics) reports day sample with :

```
    {
      "Date": "20180101",
      "Response Time": 0
    },
```
However value 0 here doesn't mean the response time is of zero seconds, it rather means there was no data to report on at all. So I guess we shouldn't have a `datatable` entry for those.

We have to remember than in later processes we should be able to sum the values and get averages (or median) on those related on the number of samples.

**Comment by creat89** [comment]
hello @mhow2, I have pushed in https://github.com/crossminer/scava/commit/8582cec9574d23130d69ae02e11e6505aa918134 some modifications to metrics that had that issue. Let me know.
Visualization Metrics modified:
- bugs.averageResponseTime
- bugs.cumulativeAverageResponseTime
- bugs.bugOpenTime
- bugs.severity.averageResponseTime
- newsgroups.averageResponseTime
- newsgroups.cumulativeAverageResponseTime
- newsgroups.severity.averageResponseTime

**Comment by mhow2** [comment]
Thanks @creat89.
One needs to redo the project analysis to get proper records in database, right ?

**Comment by creat89** [comment]
Yes, I think so. As they are based on Mongo DB and I modified when elements were stored.
