### ISSUE TITLE
register project : irc as source

### ISSUE THREAD

**Issue by nnamokon** [crossminer/scava#251]
Irc reader is now available within the platform and requires the ability to register an Irc project via the UI. Please see the project `org.eclipse.scava.repository.model.cc.irc` parameters below:

Mandatory parameters:
URL = URL for where the Irc dumps are going to be stored
NAME= Name of the Irc
DESCRIPTION = description of the Irc
COMPRESSEDFILEEXTENSION = file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)

Optional parameters (if the archive location is protected by basic authentication):
USERNAME = username
PASSWORD = password

**Comment by ambpro** [comment]
Hi, @nnamokon, 

>COMPRESSEDFILEEXTENSION = file extension of the compressed archive. (currently supports 'tarballs' (tar.gzip, tgz)

Could you please explain with more details the nature of the `COMPRESSEDFILEEXTENSION` field? 
From the `Irc` data model it should be a string! isn't it?

**Comment by ambpro** [comment]
@nnamokon, the commit 5cf097f should add a support for the irc source.
