### ISSUE TITLE
scava2es fails to upload to ES at some point

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#253]
We have the following issue that is coming back. I thought it was solved in some way, but it's not.

At the beginning of the import process, it seems to work but after ~115 chunks ES is going away

```
(...115 like follow)
2019-05-31 10:03:05,715 500 items uploaded to ES (https://admin:admin@elasticsearch:9200/scava-metrics/items/_bulk)
2019-05-31 10:03:06,219 500 items uploaded to ES (https://admin:admin@elasticsearch:9200/scava-metrics/items/_bulk)
```

Then:

```
2019-05-31 10:03:07,821 Retrying (Retry(total=20, connect=21, read=7, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /scava-metrics/items/_bulk?refresh=true
2019-05-31 10:03:08,269 Retrying (Retry(total=19, connect=21, read=6, redirect=5, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /scava-metrics/items/_bulk?refresh=true
```

**Comment by mhow2** [comment]
Maybe we need to "wait" for ES a little more, either with a timer between each chunk or better, if possible by checking if the cluster is ready to take more data.

**Comment by mhow2** [comment]
It seems I have solved the issue by tweaking `http.max_content_length` to `500mb` in the ES container. Default is `100mb`. Of course I suppose that we could either reduce the number of items per bulk.  @valeriocos could you update this config value upstream in the container config file ?

**Comment by valeriocos** [comment]
Thank you @mhow2 for reporting this issue. What do you think if we add a new env variable here:
https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-build.yml#L176 ? The variable will set the bulk-size here: https://github.com/crossminer/scava-deployment/blob/dev/dashboard/importer-scava-metrics.sh#L7

**Comment by valeriocos** [comment]
@mhow2 a PR is available on scava-deployment repo: https://github.com/crossminer/scava-deployment/pull/64. Would you mind review it, thanks ?

**Comment by valeriocos** [comment]
Can we close this issue @mhow2 ?

**Comment by mhow2** [comment]
Hi @valeriocos, OK we can close.
But as said in a previous comment here, I would tweak [`http.max_content_length`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) a little up in [acsdocker/elasticsearch:6.3.1-secured](https://hub.docker.com/r/acsdocker/elasticsearch/dockerfile) that would allow us to raise the bulk size and speed up upload (I guess).

**Comment by valeriocos** [comment]
thanks for the quick reply @mhow2 , please have a look at the PR to increase the max_content_lenght: https://github.com/crossminer/scava-deployment/pull/65

**Comment by valeriocos** [comment]
PR crossminer/scava-deployment#65 @mhow2 , let's close the issue. Feel free to reopen it if the error pops up again
