### ISSUE TITLE
Kibana Scava-Sentiment

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#254]
Hello,

I'm checking that the Kibana, when we ask for Scava-Sentiment we get the data regarding emotions instead of sentiment. Is there any particular reason for that? There are two different metrics one for sentiments and other for emotions. In the former, there are only three possible values positive, negative and neutral, which are represented as numerical values between -1 and 1. For the emotions, there are 6 different emotions: love, joy, anger, surprise, sadness and fear. They are grouped in positive (love and joy) and negative (sadness and fear) emotions. Surprise is a "neutral" case as it can be a positive surprise or a negative one.

**Comment by valeriocos** [comment]
Thank you @creat89 for opening this issue. The idea is to rework this dashboard according to what you reported (and also according to a previous comment from @mhow2 https://github.com/crossminer/scava/pull/235#issuecomment-495562622). 

If you agree, once the dashboard is ready I'll ask you to review it. Thanks

**Comment by creat89** [comment]
Cool, I didn't found issue #235, but, yes, I've seen that you have discussed that already. I'll help you if you have questions or want feedback.

**Comment by valeriocos** [comment]
@creat89 could you please have a look at the dashboard at: https://github.com/crossminer/scava/pull/274 and provide feedback ?

Thanks

**Comment by valeriocos** [comment]
PR merged: https://github.com/crossminer/scava/pull/274

I close this issue @creat89 (since the PR got positve feedback), feel free to reopen it if needed, thanks!
