### ISSUE TITLE
Like for TripAdvisor

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#260]
Would it be doable the present the comments (resp. the forums) like TripAdvisor does:
![image](https://user-images.githubusercontent.com/6196602/58785726-5fef4780-85e6-11e9-8a4d-5ec74346f4da.png)
Where instead of Excellent, Very Good, Average, Poor, Terrible, we could have Love, Joy, Surprise, Sadness, Fear and Anger.
But, the most important, if it is possible, would be able to retrieve the comments which have been rated "Terrible" by our analyser like we can do in TripAdvisor.

Does it make any sense ?

**Comment by mhow2** [comment]
Do you mean it would be the overall emotions distribution for the whole forum (all threads) of a specific project ? (related to the selected time span in Kibiter). Could be interesting for bugs comments too in our UC.

**Comment by phkrief** [comment]
yes, it is what I meant and yes, of course, it would be listed for a specific time period define in Kibana.

IMHO, for each metrics, when it is possible, we should be able to point to the code, the comment or the configuration file which contributed to the metrics

**Comment by valeriocos** [comment]
@phkrief @mhow2 please have a look at: https://github.com/crossminer/scava/pull/274 , it includes the `trip advisor` visualization

> But, the most important, if it is possible, would be able to retrieve the comments which have been rated "Terrible" by our analyser like we can do in TripAdvisor.

It doesn't seem to be possible right now, since the SCAVA API just returns aggregated data (number of comments), not the single comments.

**Comment by valeriocos** [comment]
@phkrief @mhow2 we can close this issue if you agree (since the visualization was added at: https://github.com/crossminer/scava/pull/274). We may open another issue to address what @phkrief was suggesting (`retrieve the comments which have been rated "Terrible"`)

**Comment by phkrief** [comment]
This is fine with me. Please close it and thanks again for your support.
I will create the new enhancement

**Comment by valeriocos** [comment]
you're welcome @phkrief , thanks!
