### ISSUE TITLE
dev dashboard : update default font size for avg/median... display

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#261]
![2019-06-03_10-02](https://user-images.githubusercontent.com/9987241/58786094-1e12d100-85e7-11e9-8381-d461bf6144fd.png)

a size of `18` would be enough.

**Comment by valeriocos** [comment]
It should be fixed with: https://github.com/crossminer/scava/pull/264

**Comment by valeriocos** [comment]
![Captura de pantalla de 2019-06-04 10-22-20](https://user-images.githubusercontent.com/6515067/58864262-a9a66380-86b4-11e9-9a91-193db928e9ea.png)

I have just deployed the latest version and the issue is fixed. If it's ok on your side @mhow2 , feel free to close this issue.

**Comment by mhow2** [comment]
Thanks !
