### ISSUE TITLE
possible issue with viz bugs.bugOpenTime

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#262]
on `clif-legacy` project, I have the issue https://gitlab.ow2.org/clif/clif-legacy/issues/317629#notes which I expect to fall into the viz metric `bugs.bugOpenTime` but I get an empty `datatable` instead when running the analysis on year 2018

**Comment by creat89** [comment]
@mhow2, there is a bug in GitLab reader, that was the reason why the metric wasn't generating the correct output.

**Comment by mhow2** [comment]
Thanks. Let's merge this one to #263
