### ISSUE TITLE
Register Eclipse Forums 

### ISSUE THREAD

**Issue by Danny2097** [crossminer/scava#283]
Following recent pushes and fixes to the Eclipse Forum Reader it is now ready to be registered as a source in SCAVA. @ambpro could you add them to the UI, so the user partners can start checking that the readers work correctly?

**Comment by ambpro** [comment]
Hello @Danny2097
the commit https://github.com/crossminer/scava/commit/5cf097f8509a0602bbca3d4ec51eeac8006ea0b9 should add a support for the eclipse-forums.
