### ISSUE TITLE
bugs.newbugs : zero values (JIRA)

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#303]
I've been running an analysis on project https://github.com/lutece-platform/lutece-core for year 2018, all metrics and which uses JIRA for bts. Here are the issues created that year 

http://dev.lutece.paris.fr/jira/browse/LUTECE-2223?jql=project%20%3D%20LUTECE%20AND%20created%20%3E%3D%202018-01-01%20AND%20created%20%3C%3D%202018-12-31%20ORDER%20BY%20created%20DESC

Unfortunately, I get zero values each days in the json response for metric `bugs.newbugs` from the metric-platform.

@creat89 could you take a look ?

**Comment by creat89** [comment]
For which metric(s)? Are you using the GitHub importer or are you creating a JIRA reader?

**Comment by mhow2** [comment]
- `bugs.newbugs` (specified the topic) is a metric
- I'm creating a Jira reader. But I don't understand the question because there is no way to "use a github importer" to create a jira reader.

**Comment by mhow2** [comment]
My bad. There was a small about of "1" in the ocean of zeros. Sorry.
