### ISSUE TITLE
Register Project: nntp as a source

### ISSUE THREAD

**Issue by nnamokon** [crossminer/scava#318]
Hi @ambpro 
The fields required to register NNTP project on the UI is incomplete. Please see the full parameters below:

Mandatory parameters:
`URL` - `String` - URL of the project repository
`NewsGroupName` - `String` - The newsgroup name
`Port` - `int` - The port number
Note: `Port` should be set to `119` by default but user can enter a different value. 

Optional parameters:
`Interval` - `int` - The call frequency
`Username` - `String` - Username used to log into the newsgroup channel
`Password` - `String` - Password used to log into the newsgroup channel
Note: `Interval` should be set to `10000` by default but user can enter a different value.

**Comment by ambpro** [comment]
@nnamokon  I pushed some fixes for the missing fields of the  NNTP project, could you check it out on your side?

Thanks

**Comment by nnamokon** [comment]
@ambpro While checking this, I noticed an error in one of the fields I provided earlier. Could you please change the `Name` field to `NewsGroupName`.  
Thanks

**Comment by creat89** [comment]
Hello @ampro and @nnamokon,

The change mande in https://github.com/crossminer/scava/commit/662d01a83ee86894d266010a9309159677eaf94d fixed the issue in MongoDB. The minor change is now to change the name of the field in the UI.

**Comment by ambpro** [comment]
@nnamokon @creat89 the NNTP field name has been updated in the commit (3bc5352).
