### ISSUE TITLE
Very slow task

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#319]
**I don't have a clue how it can be reproduced yet.** (Understand that I need help)
This one is different than #276 

I've been adding some projects:
https://github.com/docdoku/docdoku-plm
https://github.com/ow2-proactive/scheduling
https://github.com/INRIA/spoon

With analysis task on year 2018 with the following metrics (vizs only are listed):

```python
uScenarioMetricProvidersIds = ['org.eclipse.scava.metricprovider.indexing.commits.CommitsIndexingMetricProvider',
                               'org.eclipse.scava.metricprovider.indexing.bugs.BugsIndexingMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.bugs.BugsHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.comments.CommentsHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.requestsreplies.average.RequestsRepliesHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.newbugs.NewBugsHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.newusers.NewUsersHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.patches.PatchesHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.requestsreplies.RequestsRepliesHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.status.StatusHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.severity.SeverityHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.severityresponsetime.SeverityResponseTimeHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.severitysentiment.SeveritySentimentHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.severitybugstatus.SeverityBugStatusHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.topics.TopicsHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.unansweredbugs.UnansweredThreadsHistoricMetricProvider',
                               'org.eclipse.scava.metricprovider.historic.bugs.users.UsersHistoricMetricProvider',
                               'rascal.generic.churn.churnPerCommitInTwoWeeks.historic',
                               'rascal.generic.churn.churnPerCommitter.historic',
                               'rascal.generic.churn.churnToday.historic']

```

I'm running 3 workers with one task each as defined above (one per project):

![2019-07-18_12-36](https://user-images.githubusercontent.com/9987241/61451001-ac090800-a958-11e9-928e-1a5861dfa135.png)

In three hours, the tasks completed no more than 8 days (of 365).

I observe threads like this:
![2019-07-18_12-31](https://user-images.githubusercontent.com/9987241/61450836-4583ea00-a958-11e9-8c22-fc2641d9be63.png)
![2019-07-18_10-38](https://user-images.githubusercontent.com/9987241/61450837-4583ea00-a958-11e9-9560-531cae8ab502.png)

**Comment by creat89** [comment]
Could it be related to #210? I know for fact that applications with great verbosity, at least when executed on console, can be slower than non verbose ones. Do you see large amounts of lines printed from Restmule?

**Comment by creat89** [comment]
Sorry, I didn't see before the images. The problem seems to be at restmule level or the link between restmule and github reader. Still, the verbosity might be still the cause, as I guess the program needs to print everything before it is allowed to continue.

**Comment by mhow2** [comment]
@creat89 : the problem is there is no log activity, that's the point. The tasks are sleeping.

**Comment by creat89** [comment]
Do you have a valid token? Or is the reader being executed with a public access instead of the token based one? This should appear in the logs. If this is the case, that would explain why it needs to wait several minutes, the calls are being used too fast.

**Comment by mhow2** [comment]
I'm using a valid github token, at least as far as I can see from the admin ui.

**Comment by mhow2** [comment]
JMX available on scava-dev.ow2.org port 8192

**Comment by creat89** [comment]
Seeing this log, I guess the number of calls are running quite fast and the

**Comment by mhow2** [comment]
I can't reproduce. Will reopen if it happens again.
