### ISSUE TITLE
sonar metric ID

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#320]
Currently we have metric ID as random key in ES
![2019-07-19_11-01](https://user-images.githubusercontent.com/9987241/61528949-5ef06900-aa20-11e9-87fe-61d6e12424ab.png)

We should have something like `sonar_critical_violations`. it's a matter of concat `sonar_` with the metric keys we pass to the script it https://github.com/crossminer/scava-deployment/blob/dev/dashboard/importer-sonar-metrics.sh

**Comment by mhow2** [comment]
@valeriocos : could we have the metric ID with `sonar_` prefix as above ? So it's easier to search in a large list

**Comment by valeriocos** [comment]
Sure, the code in the PR already includes it: https://github.com/crossminer/scava/pull/322/files#diff-23b677ffd5993ad8b4df7b9ef80db806R183

**Comment by mhow2** [comment]
It works !
