### ISSUE TITLE
Problems to get projects analysed

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#326]
I have recently started using the beta.crossminer instance and I'm facing some difficulties to analyse some project. One the issue found is reported by @blueoly https://github.com/crossminer/scava/issues/325. 

It also seems that using more than a worker causes problems. When adding a second task, the system seems to freeze/crash and the workers disappear (I still have to identify the right steps to replicate it, but @blueoly restarted the instance already 2-3 times ;)). It also strange to see that a worker is called `w1` and the second one `worker1`.

A similar issue is related when deleting a task, this is what I see at: http://beta.crossminer.org:5601/#/worker

![captura_2](https://user-images.githubusercontent.com/6515067/61958347-6f28bb00-afc1-11e9-8749-02cb139d8e0f.png)

Sometimes, when creating a task, after adding the parameters (label name, single execution task type, start date 01/01/2018, end date 01/01/2019, all metrics) and clicking the save button, the parameters disappear and it isn't possible to save (even when adding again the parameters):

![captura_3](https://user-images.githubusercontent.com/6515067/61959051-d7c46780-afc2-11e9-894d-ff073ecc3771.png)
![captura_4](https://user-images.githubusercontent.com/6515067/61959058-da26c180-afc2-11e9-9e9c-d331a05f62a1.png)

**Comment by valeriocos** [comment]
@ambpro do you have any idea of what is happening?

**Comment by ambpro** [comment]
Hello @valeriocos,

>  have recently started using the beta.crossminer instance and I'm facing some difficulties to analyse some project. One the issue found is reported by @blueoly #325.

> It also seems that using more than a worker causes problems. When adding a second task, the system seems to freeze/crash and the workers disappear (I still have to identify the right steps to replicate it, but @blueoly restarted the instance already 2-3 times ;)). It also strange to see that a worker is called w1 and the second one worker1.

please, check out my reply about the issue [#325](https://github.com/crossminer/scava/issues/325#issuecomment-522581696) -:)

In summary, the analysis process data model has been changed a couple months ago. The data dumps from [M24](http://ci3.castalia.camp/dl/M24/) is no longer up-to-date and I suggest you to get ride of it and move to the new one on [M30](http://ci3.castalia.camp/dl/M30/). 

Please, let me know if this could help !

**Comment by valeriocos** [comment]
Thank you for the pointer @ambpro . I'll remove the dumped data at https://github.com/crossminer/scava-deployment/blob/dev/oss-db/Dockerfile and try it again.

**Comment by valeriocos** [comment]
It seems that the proble was related to the limited number of resources of my machine, which is not able to handle all services in the docker-compose. What worked for me was to limit the number of services (more details at: https://github.com/crossminer/scava-deployment/tree/dev#task-analysis)
