### ISSUE TITLE
missing metrics in ES for a project

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#332]
If you look at http://scava-dev.ow2.org:8601/goto/3c12242ffb9e1bf33332a22d907163f5 you won't see `spoon` in the list of projects for the metric `DITJavaQuartilesHistoric_Max`. Which is unexpected because we do have metrics available at http://scava-dev.ow2.org:8182/projects/p/spoon/m/DITJavaQuartilesHistoric

Could you investigate @valeriocos ?

**Comment by valeriocos** [comment]
Sure, I'm on it

**Comment by valeriocos** [comment]
I fetched the data from the OW2 instance and enriched it locally. I didn't detect any error (spoon data was correctly shown). So I enriched the data directly in the OW2 instance, and now I can see the missing spoon data: http://scava-dev.ow2.org:8601/goto/8fa5f78a59e679b5008bff4ee8c0b765

Feel free to close the issue @mhow2

**Comment by mhow2** [comment]
seems fixed
