### ISSUE TITLE
"Title is not available" on API documentation & Q&A posts

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#339]
Hi, 
When I launch the " API documentation & Q&A posts" on any text of my code, I get a list from stackoverflow but non of the title of the post is accessible. We see instead: "Title is not available"
![image](https://user-images.githubusercontent.com/6196602/63856595-53d71400-c9a2-11e9-913c-974b8b5eac2d.png)

Thanks for your help

**Comment by idarav** [comment]
Thank you for submitting this issue!

We have located the problem and we are working on it.
Currently we have some higher priority tasks, but after those we will get back to this.

**Comment by phkrief** [comment]
Dear @idarav 
Do you have any update on ths issue?
Thanks a lot

**Comment by idarav** [comment]
We are about to finish the other feature we are currently working on. After that we are going to focus on your issue.

We ask a little bit more patient
Thank you for your understanding

**Comment by phkrief** [comment]
Fixed
