### ISSUE TITLE
List of connectors on a project is wrong

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#346]
When trying to delete some of the automatically-generated git connectors from the cdt project, I realise that the list displayed in the "edit" page shows always the same items. Thus I cannot see the full list, neither can I delete some of them (this is needed to speed up the analysis).

In the project page: 
![Capture du 2019-09-03 16-26-18](https://user-images.githubusercontent.com/5849071/64181922-a06d9400-ce67-11e9-8407-948a90365029.png)

In the Edit page:
![Capture du 2019-09-03 16-26-35](https://user-images.githubusercontent.com/5849071/64181923-a1062a80-ce67-11e9-9d7e-79453c65dd81.png)

**Comment by ambpro** [comment]
@borisbaldassari , please let me know if 0bfc4a7 could help to fix the the connectors duplication when editing a project ?

**Comment by ambpro** [comment]
@borisbaldassari 
> When trying to delete some of the automatically-generated git connectors from the cdt project.

This deletion of a an existing connector is not yet implemented. The edition feature allows just to update exciting properties' values.
If it's helpful for your use case, I could implement it asap!?

**Comment by borisbaldassari** [comment]
@ambpro

> This deletion of a an existing connector is not yet implemented. The edition feature allows just to update exciting properties' values.
> If it's helpful for your use case, I could implement it asap!?
Yes that would be helpful, please. :-)

**Comment by borisbaldassari** [comment]
@ambpro Following our last meeting, I confirm that feature (delete connector) is required for our use case.

**Comment by ambpro** [comment]
@borisbaldassari I am working right now on both `add-connector` and `delete-connector` alongside to the exisiting `update-connector` option (the last touches).
I will pushed my works once I finish my local tests.

**Comment by ambpro** [comment]
@borisbaldassari the commit (d1e2997) should add support to delete connector from the admin-ui's edition web page.
![captured](https://user-images.githubusercontent.com/35226648/65055761-0c73f000-d970-11e9-8f5e-b98a1ef64dca.gif)

btw, the `add-connector` feature should be ready 100% soon !

**Comment by ambpro** [comment]
@borisbaldassari the commit (f92f470) added support for `adding-connectors` as well from the admin-ui's edition page.

**Comment by borisbaldassari** [comment]
Hi @ambpro I'll need to update the instance in order to validate the fix -- bad luck, your committed it at the same time as my update of the instance.. And since we have other issues to tackle I don't want to update it again right now. Depending on how we make progress on the other issues I'll update it this week. Thanks, cheers! :-)

**Comment by borisbaldassari** [comment]
Works for me! Thanks @ambpro !

**Comment by borisbaldassari** [comment]
Hum.. Not sure it doesn't mess up with task analysis, see issue #383 . Re-opening the issue.

**Comment by borisbaldassari** [comment]
Good for me.
