### ISSUE TITLE
display readable metric provider in the worker status

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#347]
![image](https://user-images.githubusercontent.com/9987241/64266180-7930c880-cf34-11e9-8cb2-63ed256a8412.png)
In this screenshot, we see that the current metric is "historic".
I believe it's one of the MP where the identifier finish by `.historic` like in `trans.rascal.api.changedMethods.historic`.
That would help a lot to have either the whole MP Id or anything that would help to identify which MP is running.

@ambpro btw I believe the accurate label is "current metric provider".
Flag @tdegueul 

Cheers

**Comment by ambpro** [comment]
Hi @mhow2,
ICYMI, the full name of the current metric provider could be shown once the cursor is hovered on the identifier.

![workers](https://user-images.githubusercontent.com/35226648/64433705-4b2bbf80-d0bf-11e9-9c2d-d6f18f6cbde4.png)

**Comment by mhow2** [comment]
thanks. I was far from finding this, really. Let's hope others do :D
