### ISSUE TITLE
[metric] Server error when fetching numberOfChanges

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#348]
I'm analysing https://github.com/orientechnologies/orientdb using OW2 instance (thanks @mhow2). 

When fetching the metrics with scava2es, a 500 server error pops up on the following URL: http://scava-dev.ow2.org:8182/projects/p/orientdb/m/numberOfChanges. However the metric is listed on http://scava-dev.ow2.org:8182/metrics/p/orientdb.

@tdegueul do you have any idea about this error? Thanks

**Comment by valeriocos** [comment]
I rexecuted the analysis for the same repo, the server error doesn't pop up anymore. However the data is empty:
```
{"id":"numberOfChanges","projectId":"orientdb","metricId":"trans.rascal.api.numberOfChanges","name":"Number of (breaking and non-breaking) API changes over time","description":"This metric depicts the number of (breaking and non-breaking) API changes over time.","type":"LineChart","datatable":[],"timeSeries":true,"ordinal":false,"x":"Date","y":"Number"}
```

The same happens for neo4j
```
{"id":"numberOfChanges","projectId":"neo4j","metricId":"trans.rascal.api.numberOfChanges","name":"Number of (breaking and non-breaking) API changes over time","description":"This metric depicts the number of (breaking and non-breaking) API changes over time.","type":"LineChart","datatable":[],"timeSeries":true,"ordinal":false,"x":"Date","y":"Number"}
```

**Comment by tdegueul** [comment]
@valeriocos, 9190b840d61bc54310243c9462fcb8a8c50d175c should fix the problem; the visualization names contained typos. Note that `changedMethods` doesn't have a visualization attached yet, so it won't be available.

**Comment by valeriocos** [comment]
great, thanks @tdegueul
