### ISSUE TITLE
Cannot interrupt task in worker

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#361]
We need to be able to stop a running task in a worker. There is a button on the worker page for that, but nothing happens when clicked. It seems @mhow2 confirmed the issue on his instance.

**Comment by ambpro** [comment]
@borisbaldassari can you check if the task-interruption works well now?

**Comment by mhow2** [comment]
It seems to work way better now !

**Comment by borisbaldassari** [comment]
Works for me too. :-)
