### ISSUE TITLE
Conflict between tasks with the same name

### ISSUE THREAD

**Issue by blueoly** [crossminer/scava#362]
I noticed that if I create two (or more) tasks with the same name under the same project, if I try to initiate any action to the second (or later) task, the action affects the first task in order. For example, if I have two tasks with the name "analysis" and I try to start/delete the second task, the first task is started/deleted.

So I propose to add a check that would not allow the creation of a task with an already used name under a project.

**Comment by ambpro** [comment]
@blueoly does the patch (344ac11) fix the issue above ?

**Comment by blueoly** [comment]
Abolutely! Thank you @ambpro
