### ISSUE TITLE
cannot find MHFJavaHistoric metric in ES

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#374]
This time I'm looking for the metric http://scava-dev.ow2.org:8182/projects/p/seed/m/MHFJavaHistoric in ES, but I can't find it:

![image](https://user-images.githubusercontent.com/9987241/65705670-35d7fe80-e089-11e9-8e1c-7a9fe127eddf.png)

Hower I can find the AHF one.

Do you have an idea @valeriocos ?
NB: I checked that the importer did finish the import with any problem this time :)

**Comment by valeriocos** [comment]
I understood you wanted to manipulate that metric (see GT10), https://github.com/crossminer/scava/blob/dev/web-dashboards/scava-metrics/scava2es.py#L327. The manipulated data is http://scava-dev.ow2.org:8601/goto/f5cd6334da538d462deb31d9a50a67f1

Do you want also the non-manipulated data?

**Comment by mhow2** [comment]
Completely forgot about that. Let's close
