### ISSUE TITLE
Local path displayed as the project name

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#381]
Hi,
When I launch a CROSSMINER project search I get a list of project with a path which seems to reference a local file, for example:
    **/Users/juri/development/git/FOCUS/dataset/MV_L/**g_jersey-json-1.9.jar.txt
I suppose it is not expected. ;-)

![image](https://user-images.githubusercontent.com/6196602/65814146-67aea980-e1de-11e9-8b19-ad20b41b8bb6.png)

**Comment by phkrief** [comment]
Dear @md2manoppello, Thx.
Where was the issue? in the plugin or in the knowledge base?
When can access to the fixed code or data ?
Thanks

**Comment by phkrief** [comment]
I found a new build on Jenkins but I didn't notice any change including in the revision number.
So, I suspect that the fix solve the issue on the knowledge base ?
![image](https://user-images.githubusercontent.com/6196602/65828649-79a35180-e29d-11e9-88af-dc361ed0a9fb.png)

**Comment by md2manoppello** [comment]
Yes, you are right.
I changed the KB behaviour.
Cheers,
Juri

Il dom 29 set 2019, 09:42 Philippe Krief <notifications@github.com> ha
scritto:
