### ISSUE TITLE
Knowledge base projects are not the same on the Dashboard

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#382]
Hi 
Talking with @borisbaldassari , I just noticed that the projects parsed then displayed on the dashboard (http://ci4.castalia.camp:5601/#/project) cannot be found when I run a search against the knowledge database with the Eclipse plugin.

In my understanding, we were suppose to have the same set of projects parsed for the knowledge base and the dashboard.

Am I wrong?

**Comment by md2manoppello** [comment]
please, have a look to #384

**Comment by phkrief** [comment]
@borisbaldassari how can we do to make both DB based on the same projects ?

**Comment by md2manoppello** [comment]
#393 pull request adds a scheduler that imports ossmeter projects each Sunday afternoon.

**Comment by md2manoppello** [comment]
please see this commit https://github.com/crossminer/scava/commit/1bbec4d53441a6eac91cd417f43fe3f09a631a39
A new resource synchronizes KB, ossmeter metric provider platform, and the dashboard.
Please use ```curl -X POST "http://ci4.castalia.camp:8080/api/artifacts/add-mpp/" -H "accept: application/xml"``` to syncronize.

**Comment by phkrief** [comment]
@md2manoppello What about the opposite?
DOes it mean that the KB will also contain the projects listed on the dashboard?

@borisbaldassari May I let you run the synchronisation? Thanks
