### ISSUE TITLE
Add a new json parser repo into the knowledge base

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#384]
Dear @md2manoppello , Dear @borisbaldassari ,

Could you add the following repo into the knowledge base:
https://github.com/sivash/JSONSparcerParser

I need it for my demonstrator. Actually I was looking for a JSON parser using a GNU license and this one is one of the few. 
Thx a lot

**Comment by md2manoppello** [comment]
Hi @phkrief ,
JSONSpacerParser project has been imported on the KB castalia instance.
The KB provides an importer to include GitHub projects to the KB by the api/artifacts/search/JSONSparcerParser resource.
You can easily use it by the swagger interface available at http://ci4.castalia.camp:8080/swagger-ui.html.

**Comment by phkrief** [comment]
Thx a lot @md2manoppello
