### ISSUE TITLE
Can we see in the Project search the license associated to the project if it exists?

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#385]
Hi

Will it be possible to display in the parameters description of a project in the Project search dialog the license attached to this project. It is a very important and useful information.
Thanks a lot

**Comment by phkrief** [comment]
Dear @geryxyz , 
Instead of closing the issue, you could assign it to the KB owner. ;-)

I created the Issue #388 to not lose this request.
Thanks

**Comment by geryxyz** [comment]
Sure. I closed it to prevent leftover issues, since it was not feasible on the client side. But of course, we will check the new fields and will provide a UI when we finished the current tasks in the queue. @idarav

**Comment by phkrief** [comment]
> Yes, it is useful but as far as we know the server does not send this kind of information to as.

So, bavese on the #389, this information is available on the KB. So, could you display it with the search results?
Thanks a lot

**Comment by phkrief** [comment]
Folks, 
I have to switch it a bug because we need it to fulfill the requirement U115.
Sorry about that.
Kind regards

**Comment by phkrief** [comment]
Dear @geryxyz 
Any update on this issue?
Thanks a lot

**Comment by geryxyz** [comment]
It is in the deployment queue; we ask a bit more patient. We have several higher priority tasks to complete.

**Comment by phkrief** [comment]
Dear @geryxyz ,
I'm patient. I just need to have an idea of when I will be able to cover the whole scenario we were planning.
So, If you tell me later this week, this fine. Next week this is fine too. In January, this is fine as well and in all these cases, I will be able to inform Scott and Davide about our delay. If I have no date I can't organise myself. 
Thx for your understanding

**Comment by idarav** [comment]
Dear @phkrief 
the newest version of the updatesite of the plug-in with the fix for this issue is available at: http://ci5.castalia.camp:8080/job/scava-ide/job/dev/lastSuccessfulBuild/artifact/eclipse-based-ide/org.eclipse.scava.root/releng/org.eclipse.scava.update/target/repository/

**Comment by phkrief** [comment]
Dear @idarav,

I get the following error when I try to update the plugin:

An error occurred while collecting items to be installed
session context was:(profile=_Applications_eclipse_java-2019-09_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://ci5.castalia.camp:8080/job/scava-ide/job/dev/lastSuccessfulBuild/artifact/eclipse-based-ide/org.eclipse.scava.root/releng/org.eclipse.scava.update/target/repository/plugins/org.eclipse.scava.plugin_1.18.0.rev0.jar.
Premature end of Content-Length delimited message body (expected: 1565357639; received: 1247761448

Any idea?
Thx

**Comment by geryxyz** [comment]
Dear @phkrief,
Do you entered the correct url? It should be ended with /repository/ not with the jar itself? Are you able to download the mentioned jar manually? Have you tried a clean install without updating? The file is rather large, maybe you have some limitations in your network or in the Eclipse? You could also try to download the whole folder as a zip and using a local update site.

**Comment by phkrief** [comment]
Hi @geryxyz ,

I used the Check for update feature like I did for 1.15.275.rev0 version. As you certainly know, when you created a p2 site, the PDE Eclipse feature stores our plugins and your features as jars. Then the install feature checks the root directory of your site to retrieve the description of your features and plugins then it starts downloading the jar.
The issue seems to happen during this phase
To make it short, yes, I used the correct URL and I didn't specify any jar. :-)

I don't know if you tried to reproduce the problem On my side, I tried to uninstall then reinstall the plugin. And it worked! Thx a lot

BTW, I'm surprised by the size of the jar:
![image](https://user-images.githubusercontent.com/6196602/70232423-b50a4280-175c-11ea-9895-688e510fcf85.png)
1.5GB ! Is it expected?
Thanks
Kind regards

![image](https://user-images.githubusercontent.com/6196602/70215485-ddcf0f80-173d-11ea-8814-048260609971.png)

**Comment by phkrief** [comment]
So, now I can see the license of each libray! This is great! Thx

**Comment by jdirocco** [comment]
Dear Philippe,
I was wondering about the size of the plugin, and I had the same issue when I was installing the plugin. I used a temporary fix that allows me to install the plugin. I locally downloaded the p2 repository from here, and the plugin has been installed as a local repository. It solves the installation issue. I updated the plugin and the functionalities that I used properly work.
Cheers,
Juri

**Comment by phkrief** [comment]
Dear @md2manoppello 

Do you know why the plugin is so big?
Thanks

**Comment by tdegueul** [comment]
Dear all,

The Eclipse plug-in embeds the runtime of Rascal/M3 (`org.eclipse.scava.java.m3`, ~150MB). Diving a bit into the `org.eclipse.scava.plugin` JAR, I see the following:

```
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.1
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.2
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.3
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.4
```

These 5 files are identical, only the first one should be kept and the other removed (which would remove 500MB from the JAR). Does anyone know why we have these 5 files?

**Comment by geryxyz** [comment]
> Dear all,
> 
> The Eclipse plug-in embeds the runtime of Rascal/M3 (`org.eclipse.scava.java.m3`, ~150MB). Diving a bit into the `org.eclipse.scava.plugin` JAR, I see the following:
> 
> ```
> -rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar
> -rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.1
> -rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.2
> -rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.3
> -rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.4
> ```
> 
> These 5 files are identical, only the first one should be kept and the other removed (which would remove 500MB from the JAR). Does anyone know why we have these 5 files?

Thanks for the investigation, we will check it!

**Comment by idarav** [comment]
Solved. Build is now 346 MB

**Comment by phkrief** [comment]
Indeed! It is much faster to install :-)... I could directly install the new release 1.20 on my machine...

So what was the issue, @idarav ? Why the plugin was so huge?

**Comment by idarav** [comment]
I'm glad to hear!

It was so huge, because everytime the Jenkins started a building, it download one of our dependecy libararies from an URL without checking if it's already been download, so a lot of copies was created of that jar (which is ~150MB). And then, at the last stage all of those copies was archived into the final JAR

**Comment by phkrief** [comment]
Thx a lot for your great help, @idarav. I really appreciate
