### ISSUE TITLE
Can the KB provide the license attached to a project

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#388]
Base on the Issue  #385 reply, this demand should be asked to the owner of the KB.
It will be helpful to see the license attached to the project selected in the Search Dialog.
Thanks

**Comment by creat89** [comment]
@phkrief, I'm not charged of the KB, I just created a recommender for the KB that it's based on the data processed by Scava if it is indexed.

**Comment by md2manoppello** [comment]
The IDE should not be updated.

**Comment by phkrief** [comment]
Dear @md2manoppello , Are you saying that this information doesn't make sense ?
Thx

**Comment by md2manoppello** [comment]
Hi @phkrief ,
no, I'm saying that the feature has been implemented on server-side (KB). So, the plugin shouldn't be updated because of the external behavior is not externally changed.

**Comment by phkrief** [comment]
Oh?! So the KB collects the licence information and the plugin should be able to disply it when we select a project in the Research Project dialog. Correct ?

**Comment by md2manoppello** [comment]
sorry, you are right, the dialog should be updated. :(
