### ISSUE TITLE
Stack Traces window should have a horizontal scroll

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#394]
As you can see in the image,it's impossible to see all the stack traces and there is no horizontal scroll:

![image](https://user-images.githubusercontent.com/17121539/65969753-3abbfa00-e45d-11e9-9e26-969b7f4010c1.png)

This happens, at least in the latest version of Firefox 69.0.1

**Comment by blueoly** [comment]
Yes, you have to copy the log you want to examine and paste it somewhere else to be able to read all of it. Also, the lines are not divided correctly.

**Comment by ambpro** [comment]
The commit (8b2f760c36e39f6d82e0e42968444732fac93977) should fix this issue!
