### ISSUE TITLE
Building process breaking as RESTMULE is not yet built by Jenkins

### ISSUE THREAD

**Issue by creat89** [crossminer/scava#403]
Hello,

Previously, our BTS GitHub Reader based on RESTMULE was using manually created jars to work. However, since RESTMULE has been added properly to the dev branch and it is capable of being built using Jenkins, it makes more sense to stop using the manually produces jars.

I have done the migration by adding the RESTMULE plugins as dependencies of the BTS GitHub Reader and updated the features.xml file. Everything runs perfectly on Eclipse.

However, when I tried to build the metric-platform on my computer, the dependencies are not found. In fact, I get the following issue:

```
[INFO] Resolving class path of MavenProject: org.eclipse.scava:org.eclipse.scava.factoid.bugs.hourly:1.0.0-SNAPSHOT @ E:\scava_EHU_dev\scava\metric-platform\factoids\org.eclipse.scava.factoid.bugs.hourly\pom.xml

[INFO] Computing target platform for MavenProject: org.eclipse.scava:org.eclipse.scava.factoid.bugs.responsetime:1.0.0-SNAPSHOT @ E:\scava_EHU_dev\scava\metric-platform\factoids\org.eclipse.scava.factoid.bugs.responsetime\pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.scava:org.eclipse.scava.factoid.bugs.responsetime:1.0.0-SNAPSHOT @ E:\scava_EHU_dev\scava\metric-platform\factoids\org.eclipse.scava.factoid.bugs.responsetime\pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.scava.factoid.bugs.responsetime 1.0.0.qualifier
[ERROR]   Missing requirement: org.eclipse.scava.platform.bugtrackingsystem.github 1.0.0.qualifier requires 'bundle org.eclipse.scava.crossflow.restmule.dependencies 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.scava.factoid.bugs.responsetime 1.0.0.qualifier depends on: bundle org.eclipse.scava.metricprovider.historic.bugs.responsetime 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.scava.metricprovider.historic.bugs.responsetime 1.0.0.qualifier depends on: bundle org.eclipse.scava.metricprovider.trans.bugs.requestsreplies 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.scava.metricprovider.trans.bugs.bugmetadata 1.0.0.qualifier depends on: bundle org.eclipse.scava.platform.bugtrackingsystem.github 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.scava.metricprovider.trans.bugs.requestsreplies 1.0.0.qualifier depends on: bundle org.eclipse.scava.metricprovider.trans.bugs.bugmetadata 0.0.0
[ERROR]
```

As you can observe on the stack trace, one of the plugins on which we depend, is not being found. And the reason for that is quite logic, RESTMULE plugins are not within the scope of the metric-provider POM.xml, they are in the POM file found in  `org.eclipse.scava.crossflow.restmule.parent`.

So, what do I need to do or have to be done to solve this issue?

**Comment by creat89** [comment]
It seems that the issue was a wrong build.properties file. I'll open it again if I have the problem  again or if the build doesn't pass Jenkins.

**Comment by creat89** [comment]
Well, my build broke after the changes. I guess that in my computer it built because at a certain point I did a `mvn clean install -DskipTests` on Restmule folder. However, Jenkins do not auto build yet Restmule, thus, it couldn't find the built version of restmule.

**Comment by geryxyz** [comment]
I do not got perfectly what's this issue about, but to be on the safe side: does it have anything to do with the CROSSMINER Eclipse IDE plug-in?

**Comment by creat89** [comment]
@geryxyz, no, it doesn't have nothing to with Eclipse Plug-in.  This is related to issue This issue is related to issue https://github.com/crossminer/scava/issues/133
