### ISSUE TITLE
Fix jenkins build issue for plug-in

### ISSUE THREAD

**Issue by Szamos96** [crossminer/scava#406]

**Comment by borisbaldassari** [comment]
@Szamos96 You cannot enter a bug without any description or information. Please provide some logs, description of the issue or...

**Comment by borisbaldassari** [comment]
@Szamos96 We don't have any information about the build #406 on the CI platform, the build runs fine.. what is your problem actually?

**Comment by geryxyz** [comment]
Thanks for the reminder. This issue is kinda obsolete since the reset the CI build done by @tdegueul (if I remember correctly) fixed the build process. We planned to fix any build process-related error under this issue, but we found none of those.
