### ISSUE TITLE
project edit : cannot save communication channels setttings

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#409]
When you hit the save button and re-enter the settings it's gone.
Could have a link with #252 

![Peek 18-10-2019 11-42](https://user-images.githubusercontent.com/9987241/67084317-035b8600-f19d-11e9-89e2-220cef0d682e.gif)

Could you have a look please ? @ambpro @crossminer/sft

**Comment by ambpro** [comment]
@mhow2 , as we discussed earlier, the probleme is due to unfilled mandatory field (executionFrequency). So, I pushed a fix (12d95ae) to validate fields when adding a new connector within the pop-up.
Let me know if it works as expected now ?

**Comment by creat89** [comment]
Even if the execution frequency field is filled, the DB is not storing all the data as indicated in https://github.com/crossminer/scava/issues/252#issuecomment-537427108
I'll test the last version as soon as Jenkins finishes to see if this has been fixed.

**Comment by ambpro** [comment]
@mhow2 @creat89 , could you check again if the previous commits fix the issue?

**Comment by mhow2** [comment]
So I have redeployed the stack. I have added Communication channels settings to one of my existing project : http://scava-dev.ow2.org:5601/#/project/configure/bonitaengine

Then I hit the button "restart" and the task change to state "ERROR".

No error reported in the slave container. The last line is:
`oss-slave2_1      | Storage initialised!`

What should I do now ?

**Comment by creat89** [comment]
Can you tell us which communication channel were you testing? I'll try to reproduce the error. I have never seen a similar error.

**Comment by mhow2** [comment]
sorry, it is the systematic reader that I'm testing here.

**Comment by mhow2** [comment]
But you should have an existing project with already existing metrics in order to be in the same kind of scenario as I am.

**Comment by creat89** [comment]
Well, there is something weird. Checking the stack traces on the platform I have found this (the same for worker 2 and worker 3:
```
bonita-engine 	ProjectAnalyser: Delta creation 
	java.lang.RuntimeException: java.lang.RuntimeException: Error executing call to webservice. 
[401,https://bonita.atlassian.net/rest/api/2/search?startAt=0&maxResults=50&jql=project+%3D+%22BBPMC%22+AND+%28updated+%3E%3D+%222018%2F01%2F01+00%3A00%22+OR+created+%3E%3D+%222018%2F01%2F01+00%3A00%22%29&fields=*all%2C-issuelinks]at 
org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.getNextPage(JiraIssueIterator.java:52)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.hasNext(JiraIssueIterator.java:37)
at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.cacheItems(Cache.java:105)at 
org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.update(Cache.java:69)at 
org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.getItemsAfterDate(Cache.java:53)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:102)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:1)at 
org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)at 
org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)at 
org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:73)at 
org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:103)at 
org.eclipse.scava.platform.osgi.services.TaskExecutor.run(TaskExecutor.java:26)at 
java.lang.Thread.run(Thread.java:748)Caused by: java.lang.RuntimeException: Error executing call to webservice.
 [401,https://bonita.atlassian.net/rest/api/2/search?startAt=0&maxResults=50&jql=project+%3D+%22BBPMC%22+AND+%28updated+%3E%3D+%222018%2F01%2F01+00%3A00%22+OR+created+%3E%3D+%222018%2F01%2F01+00%3A00%22%29&fields=*all%2C-issuelinks]at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.executeRestCall(JiraRestClient.java:183)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:166)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:156)at 
org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.getNextPage(JiraIssueIterator.java:50)... 12 more
 	w2 	28/10/2019 	01/01/2018
```

**Comment by creat89** [comment]
I have reproduced the previous error, but it has nothing to do with an error on the platform. I have contacted @mhow2 privately to solve the issue.

**Comment by mhow2** [comment]
It was about the JIRA reader that had a wrong password, but nothing in the UI's really helped to quickly indentify the problem, but to read on the stack trace section on @creat89's advice. And find something about 401.
That would be so much useful to provide a meaningful error message directly from the tasks view...

**Comment by ambpro** [comment]
@mhow2 @creat89 can you reproduce this issue again?  I have pushed a fix related to the fields validation !

**Comment by mhow2** [comment]
looks good
