### ISSUE TITLE
is mingration a typo?

### ISSUE THREAD

**Issue by md2manoppello** [crossminer/scava#41]
@MarcioMateus 
https://github.com/crossminer/scava/blob/e8cdc23b9feedd3838c4c097da4f0ecc76fee906/metric-platform/releng/org.eclipse.scava.configuration/pom.xml#L43

**Comment by tdegueul** [comment]
It used to be a typo in the directory structure itself, but we fixed it. The typo you meantion in the POM file hasn't been caught since it was only used at the very beginning to generate default `pom.xml` for every plugin. But you can safely fix it ;)
