### ISSUE TITLE
Rename Kibiter viz "non resolved/closed bug"?

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#411]
For project sat4j , where issues are at https://gitlab.ow2.org/sat4j/sat4j/issues I got the following visualization in Kibiter:

![image](https://user-images.githubusercontent.com/9987241/67850335-84edd500-fb08-11e9-8e27-cc47022097e7.png)

It shows about 147 bugs that are "non resolved/closed". First I wonder if it would be less confusing to call the viz "open bugs" instead of introducing a negative statement. WDYT @valeriocos ?

Then I don't understand the number "147".
What I can see is it's consistent with the metric raw data at http://scava-dev.ow2.org:8182/projects/p/sat4j/m/bugs.nonResolvedClosedBugs ,so it's not a problem with the dashboard but rather with how the thing is computed in relation to GitLab. @creat89 do you have an explanation ?

Regards,

**Comment by creat89** [comment]
Checking the code, the one charged of setting that a bug is closed works for gitlab. I'm thinking that the issue comes from historic metric that calculates a cumulative historic metric and it doesn't reduces the number of open issues. I'll check the code later or tomorrow, as right now I'm on the phone.

**Comment by valeriocos** [comment]
> It shows about 147 bugs that are "non resolved/closed". First I wonder if it would be less confusing to call the viz "open bugs" instead of introducing a negative statement. WDYT @valeriocos ?

I'm fine with any decision. Should I rename `Non resolved/Closed bugs` with `Open bugs`?

**Comment by mhow2** [comment]
If I sum 148 "non resolved/closed bug" + 8 "fixed bug" reported in the last day for the viz , it is about 156 bugs, which is close to the 158 "all bugs" reported in GitLab...

**Comment by creat89** [comment]
Hello @mhow2,

The platform is retrieving correctly the number of bugs. Two of them were updated before 2018:
![image](https://user-images.githubusercontent.com/17121539/67944774-26425d00-fbd5-11e9-9638-963fab6f4a5d.png)

I have opened another issue (https://github.com/crossminer/scava/issues/416) regarding the number of closed issues in GitLab.

**Comment by mhow2** [comment]
> I'm fine with any decision. Should I rename Non resolved/Closed bugs with Open bugs?

I mean, you could have your own opinion :) As soon as the title of the viz mention "fixed and open", it looks more consistent to me to replace "non resolved/closed" by "open". And we don't need to mention "bugs" in labels as it's easy to deduce we're talking about bugs.
So I would put labels as "open" and "fixed". Or maybe "fixed/resolved" to take into account the JIRA case wdyt @creat89

**Comment by valeriocos** [comment]
A PR is available at: https://github.com/crossminer/scava/pull/422, the new labels are "open" and "fixed/resolved"

**Comment by valeriocos** [comment]
Fixed with #422 , thanks
