### ISSUE TITLE
scava-overview dashboard : "last facts" vs "recommendations"

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#419]
Believing the screenshot, scava-overview dashboard filtered on project XWiki and sorted by date, it seems that "last facts" and "recommendations" are about the same ("recommendations" contains an additional project column).

![image](https://user-images.githubusercontent.com/9987241/68302221-df0b0f00-00a1-11ea-93f0-4416d98bfb27.png)

Is there an explanation for it ? Isn't the term "recommendation" about the KB service ?

**Comment by valeriocos** [comment]
The recommendations table shows facts about the rascal metrics. If you open the visualization you can see the list of metrics:
![captura_125](https://user-images.githubusercontent.com/6515067/68303838-f26ba980-00a4-11ea-8337-9d2e7a3bd252.png).

On the other hand, `last facts` shows the facts ordered by date.

**Comment by mhow2** [comment]
> The recommendations table shows facts about the rascal metrics

It seems the last facts show those too, that's the point. both viz look about the same

**Comment by valeriocos** [comment]
yes, because the "recommendations" are a subset of all facts. What do you suggest @mhow2 ?

**Comment by mhow2** [comment]
@borisbaldassari :
"recommendations" metrics is a subset of factoids metrics, eg rascal ones.
"last facts" contains all metrics (that includes rascal ones).

It was the result of the work in https://github.com/crossminer/scava-deployment/issues/42 and especially https://github.com/crossminer/scava-deployment/issues/42#issuecomment-470488717

I'm trying to understand how "COCOMO" can turn into a recommendation (#421) and if we shouldn't rather leave it for the "last facts" table.
I'm also wondering if we shouldn't simply remove all rascal metrics from "last facts" ? So we consolidate the spirit of have two tables for two separate purpose instead of mixing up.

WDYT ?

**Comment by borisbaldassari** [comment]
@mhow2 for the sake of visual consistency, it sounds good to have them separated and not showing up twice. m2c. :-)
As for cocomo, you have to be warned that it's been debunked a couple of times and it may show really weird numbers..

**Comment by valeriocos** [comment]
Fixed with #426
