### ISSUE TITLE
Metric providers cannot be found

### ISSUE THREAD

**Issue by blueoly** [crossminer/scava#424]
In the latest deployments of the platform using the docker images, I observed that a certain Metric Provider is missing, something that did not happen previously and I have made no changes to this metric provider (Docker antipatterns metric-provider). @ambpro told me he can find it when he deploys the platform from source. So, maybe something wrong happens during the CI process.

This may happen to other metric providers too. I have not observed it about others but it could be possible.

**Comment by MarcioMateus** [comment]
I did the metric-platform build from the command line using `mvn clean install -DskipTests` and I also couldn't find the `org.eclipse.scava.metricprovider.trans.configuration.docker.antipatterns.DockerAntipatternTransMetricProvider` when calling `http://localhost:8182/analysis/metricproviders`. However, I found the metric providers corresponding to the Docker dependencies and smells. I checked the configuration files and it seems to be similar.

I tried to check and do some modifications to the configuration files of the metric-provider and of the metric-platform but with no success.

Does anyone have any idea of what may be causing this behaviour.

**Comment by tdegueul** [comment]
I had a quick look without success. The platform indeed builds the project ([see the logs](http://ci5.castalia.camp:8080/job/scava-metric-platform/job/dev/587/consoleText)), the resulting platform ZIP file contains the associated JAR too, and the [feature.xml](https://github.com/crossminer/scava/blob/dev/metric-platform/platform/org.eclipse.scava.platform.feature/feature.xml) includes it. I have no idea :(

**Comment by blueoly** [comment]
@MarcioMateus this is strange because @ambpro told me that when he built the platform from source, he could find the metric provider http://localhost:8182/analysis/metricproviders.

**Comment by ambpro** [comment]
@blueoly 
>I did the metric-platform build from the command line using mvn clean install -DskipTests and I also couldn't find the org.eclipse.scava.metricprovider.trans.configuration.docker.antipatterns.DockerAntipatternTransMetricProvider when calling http://localhost:8182/analysis/metricproviders. 

@MarcioMateus tested the metric-platform build manually using `maven` and `tycho` and he didn't check the code source using an IDE (as I did previously). Here you can find a screenshot of a docker anti-pattern metric from the `http://localhost:8182/analysis/metricproviders` API request 
![docker-antipattern](https://user-images.githubusercontent.com/35226648/68684495-df574e80-0568-11ea-8347-d47c20940843.png)
@MarcioMateus could you confirm that ?

**Comment by MarcioMateus** [comment]
@ambpro, yes
I did the build without using Eclipse IDE. Only `maven`  and `tycho` on the command line, and file modifications with with a file editor.   `http://localhost:8182/analysis/metricproviders` didn't return the docker anti-pattern metric provider when running the binaries built (mac os X version).

**Comment by creat89** [comment]
Hello @blueoly,

I think I know the reason because in the past I used see these issues. In the build.properties of `org.eclipse.scava.metricprovider.trans.configuration.docker.antipatterns` is not indicated that the bin  should include the file _plugin.xml_. It should be just that.

**Comment by creat89** [comment]
Commit https://github.com/crossminer/scava/commit/d9bcde31c6308fe33382f52f0edf1222edca25c0 should fix the error ;)

**Comment by creat89** [comment]
BTW, not including the _plugin.xml_ in the build.properties does not raise any error on Eclipse, but a warning. That's why it can go so easily unnoticed. As well, that's why in Eclipse it can run perfectly, but when you use the binaries the plug-in cannot be found.

**Comment by MarcioMateus** [comment]
Many thanks @creat89 !!!
I confirm that this fix solved the issue on my side.

**Comment by blueoly** [comment]
Ok...... Many many many thanks @creat89 !

I close the issue.
