### ISSUE TITLE
"Metric Interface" menu item doesn't seem to work

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#430]
Hi 
I discovered recently this new item on the top menu:
![image](https://user-images.githubusercontent.com/6196602/69043228-f4adfc00-09f2-11ea-8b08-d7f69474b76d.png)

What is the purpose of this item?
When I try to launch it, it starts running and it blocks my Eclipse workbench forever. The only option I have is to kill the process.

Thanks

**Comment by geryxyz** [comment]
If I remember correctly it is just a debugging feature and will excluded from the final version. @Szamos96?

**Comment by Szamos96** [comment]
That menu item is only for debugging purposes. It will removed from the final product.

**Comment by Szamos96** [comment]
@phkrief Can we close this issue?

**Comment by phkrief** [comment]
Sure!
