### ISSUE TITLE
We must restart the workbench if we change the KB server URL

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#441]
In the preferences, if we change the KB server URL, we must restart Eclipse to see the impact else the requests go on the previous server.

It is a minor issue

**Comment by geryxyz** [comment]
We checked in the current version, both during execution and in the source and there is no indication on our side that the plug-in has to be restarted. Could you please specify your exact steps and plug-in version if the problem still present?

**Comment by phkrief** [comment]
Dear @geryxyz , 
I'm not talking about the server here. I'm talking about the Eclipse IDE that I have to restart when I change the preferences.
Kind regards

**Comment by geryxyz** [comment]
Yes, I understand it (my bad, I meant the plug-in), but it is not required at the plug-in side. We cannot reproduce this on our side. We are able to change the server url without restarting the Eclipse. Please specify the exact steps you made and the client version you used.

**Comment by phkrief** [comment]
The last tests I made against the ow2 instance could not reproduce this issue.
Thanks a lot
