### ISSUE TITLE
Plug-in too big

### ISSUE THREAD

**Issue by geryxyz** [crossminer/scava#444]
The Eclipse plug-in embeds the runtime of Rascal/M3 (`org.eclipse.scava.java.m3`, ~150MB). Diving a bit into the `org.eclipse.scava.plugin` JAR, I see the following:

```
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.1
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.2
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.3
-rw-r--r--  1 dig dig 148M  4 déc.  20:58 org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar.4
```

These 5 files are identical, only the first one should be kept and the other removed (which would remove 500MB from the JAR). Does anyone know why we have these 5 files?

_Originally posted by @tdegueul in https://github.com/crossminer/scava/issues/385#issuecomment-562105088_

**Comment by idarav** [comment]
Solved. Build is now 346 MB
