### ISSUE TITLE
import projects from URL : GitLab

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#55]
As seen in the UI:

> If your project is hosted on Eclipse, SourceForge, or GitHub, you can simply paste the URL below and we'll add it.

As our use case is about GitLab for issues, would it be possible to add it ? @yannisKork and his team will provide miners for GitLab.

**Comment by tdegueul** [comment]
Hi @mhow2,

We indeed need some support for GitLab. I haven't developed a forge connector myself yet, but here are some pointers on how it is done for GitHub:

https://github.com/crossminer/scava/tree/master/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github
https://github.com/crossminer/scava/tree/master/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github.importer

Intuitively, it should be possible to add GitLab support following a similar pattern. Can we collaborate on this to make it happen?

**Comment by md2manoppello** [comment]
I implemented all the forges importers on ossmeter platform. 
Read it if you are unfamiliar to Pongo and how to generated ODM classes form metemodels (object document mapper).
The first pointer point to a folder that contains the generated files by Pongo (https://github.com/kolovos/pongo) .
Pongo takes metamodel (both .ecore and .emf files are allowed) as input and generates the ODM classes.
In this particular case, github.ecore extends the crossminer.ecore metamodel that is available at https://github.com/crossminer/scava/tree/master/metric-platform/platform/org.eclipse.scava.repository.model/src/org/eclipse/scava/repository/model/crossmeter.ecore .
Please resemble Github model and importer to support the new GitLab forge.

**Comment by mhow2** [comment]
Hi @tdegueul, if you need something from us (OW2) at this point, don't hesitate to ask.
By the way, thank you for the notes @md2manoppello

**Comment by davidediruscio** [comment]
Added also @yannisKork in the loop.

**Comment by davidediruscio** [comment]
@tdegueul Can we close this issue? I think you developed the GitLab importer right?

**Comment by mhow2** [comment]
I have tested the feature and it works. We can close that one and open further issue when appropriate.
Before closing, we want to make sure the following text from the Admin UI is updated (ie, adding GitLab):
![2019-03-04_16-07](https://user-images.githubusercontent.com/9987241/53741926-be960f80-3e97-11e9-91ad-d11c434f251b.png)

Note that the GitLab's issues reader from @crossminer/ehu still has to be tested. The above just provides the necessary metadata for the reader, reader that I've been told by @creat89 was ready to test on their branch and I have to take a look.

**Comment by creat89** [comment]
@mhow2, commit https://github.com/crossminer/scava/commit/b243dd5d0a48c1bc893a92a03d8c276f93dcc85c should make available to import a GitLab project from URL.
