### ISSUE TITLE
New Analysis Task : form / "save" button not working propertly

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#57]
In the form view "New Analysis Task" within the Admin UI.
When you hit the save button without filling all the required fields beforehand, the button turns grey and nothing more happen. To retry, the only workaround is to click "projects" in the left panel and fill it as it needs to (btw we don't know which are mandatory fields).

```
The errors in the back kitchen when it happens:
oss-app_1_a7edab0a86f8 | Nov 20, 2018 3:31:22 PM org.restlet.resource.ServerResource doCatch
oss-app_1_a7edab0a86f8 | WARNING: Exception or error caught in server resource
oss-app_1_a7edab0a86f8 | Internal Server Error (500) - The server encountered an unexpected condition which prevented it from  fulfilling the request
(stack trace)
oss-app_1_a7edab0a86f8 |        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
oss-app_1_a7edab0a86f8 |        at org.restlet.resource.ServerResource.post(ServerResource.java:1376)

oss-app_1_a7edab0a86f8 | Nov 20, 2018 3:31:22 PM org.restlet.engine.log.LogFilter afterHandle
oss-app_1_a7edab0a86f8 | INFO: 2018-11-20       15:31:22        172.19.0.11     -       172.19.0.7      8182    POST    /analysis/task/create -       500     486     145     10      http://oss-app:8182     Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0  http://wacke.ow2.org/project/configure/RocketChat/add-task
```

**Comment by ambpro** [comment]
@mhow2  I fixed the issue:)

**Comment by borisbaldassari** [comment]
@ambpro hey cool, what did you do, how can we get the fix? Facing the same problem here. :-)

**Comment by ambpro** [comment]
@borisbaldassari the fix is committed and merged in the dev branch ([here](https://github.com/crossminer/scava/commit/58560b199d87a09737849929fffc78b96d52e77e))

**Comment by mhow2** [comment]
Thanks @ambpro !
In case you're not aware about, you can also mention an issue with #57 in the commit message so it gets automatically mentioned in the issue here.

**Comment by mhow2** [comment]
Hi @ambpro, deployed again this morning. What am I doing wrong ? The "save" button is still greyed.

![screenshot_2018-12-06 crossminer administration 1](https://user-images.githubusercontent.com/9987241/49573563-92253280-f93e-11e8-9ecf-51a98ce163f8.png)

**Comment by ambpro** [comment]
Hello @mhow2, I guess it's because the whitespace between words on the label name

**Comment by ambpro** [comment]
@mhow2, I can provide a hotfixing quickly by allowing whitespace on the HTML inputs.

**Comment by borisbaldassari** [comment]
I believe the fix doesn't work for me: 
* I can create a task named "task 1" (only one space) but then it doesn't show up in the list.
* I cannot create a task name "task  2" (two spaces) because it says: only numerical characters blabla.
* When I create the same task (i.e. same properties) with no space, e.g. task_1 then it shows up..

**Comment by borisbaldassari** [comment]
Right after doing the afore-mentioned steps the instance fails: list of projects, workers and tasks are all empty. Definitely re-opening.

**Comment by borisbaldassari** [comment]
Screenshots of the previous description.

![capture du 2019-02-03 14-05-22](https://user-images.githubusercontent.com/5849071/52177534-a5c80a80-27c2-11e9-9f9b-7eb0cd3a9415.png)
![capture du 2019-02-03 14-07-26](https://user-images.githubusercontent.com/5849071/52177535-a5c80a80-27c2-11e9-8ac5-4b2b7447ec94.png)

**Comment by mhow2** [comment]
I think it is fixed. Closing
