### ISSUE TITLE
new project with VCS (git) URL : no metric in mongodb

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#60]
Yesterday, I realized that the project I've been provisioning in the admin was not appearing in mongo db.
I used the Projects > Create project > Filled the CVS URL with https://gitlab.ow2.org/sat4j/sat4j.git
The project is added in the UI with no error.

Then in the mongodb shell:

```
> use SAT4J
switched to db SAT4J
> show collections
> (nothing)
```
With @tdegueul we think the source code is even not checked out.

**Comment by ambpro** [comment]
I arrived to import the https://gitlab.ow2.org/sat4j/sat4j.git project successfully and store it on the mongodb databaseas as shown here 
<a href="https://ibb.co/MB7GC9p"><img src="https://i.ibb.co/MB7GC9p/sat4j.jpg" alt="sat4j" border="0"></a>

**Comment by mhow2** [comment]
Currently, I cannot try to reproduce the issue because I'm blocked with #63

**Comment by mhow2** [comment]
As of today, when reproducing I'm able to get some metrics in the dashboards so I assume it's fixed. (but notice it's not specified here how the problem has been solved).

**Comment by ambpro** [comment]
I never was able to reproduce this issue.

**Comment by mhow2** [comment]
OK, so closing !
