### ISSUE TITLE
signup form : success message but mail is not sent successfully

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#61]
Hi,

I'm writing about that [screen](https://nextcloud.ow2.org/index.php/s/WQLYkc6xydAcNfn/preview)

At the same time I get in the logs:

```
auth-server_1_89645e84ca25 | 2018-11-22 11:12:20.590  WARN 1 --- [nio-8085-exec-9] o.e.s.authservice.service.MailService    : Email could not be sent to user 'xxx@ow2.org': Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuJ
auth-server_1_89645e84ca25 | 534-5.7.14 memUpLHrxlL1-IkGbbkE5QZGd9u4oV_YVrqSei3BQn84SeoeumXA4RQpngMp4KQys05dGe
auth-server_1_89645e84ca25 | 534-5.7.14 IZc4L69iHmQyUMB6lll9r1mFlqa4Ttigx1e_EZRCEzZyW5QOUzfTiwWSZfj53dTB71Dywv
auth-server_1_89645e84ca25 | 534-5.7.14 z6sEMIMfaU8A5EqoA5N9mvz36v6hAx4ZAW_5LL4UPeAbNZcA-Yjz160xW79cmEwD49Vrtv
auth-server_1_89645e84ca25 | 534-5.7.14 ksv0fMVURas42z-g8y00ivplGs46AX4CaId1QnIpjkzfrdHTYl> Please log in via
auth-server_1_89645e84ca25 | 534-5.7.14 your web browser and then try again.
auth-server_1_89645e84ca25 | 534-5.7.14  Learn more at
auth-server_1_89645e84ca25 | 534 5.7.14  https://support.google.com/mail/answer/78754 g198sm5528734wmd.23 - gsmtp
```

So it tells us the mail sending has failed : the UI might reflect that is some way.

**Comment by ambpro** [comment]
@mhow2 could you provide the config file of SMTP mail service?

**Comment by mhow2** [comment]
> @mhow2 could you please provide the config file of SMTP mail service?

Yes of course, it is the one shipped within scava-deployment repo in [dashboard-plus-admin/auth/application.properties](https://github.com/crossminer/scava-deployment/blob/dashboard-plus-admin/auth/application.properties)

**Comment by ambpro** [comment]
@mhow2 I coudn't reproduce this issue either locally or on aws instance using the default provided config.

**Comment by mhow2** [comment]
this is strange. I cannot reproduce 100%. I got it working once today, ever others attempt led to  the original report.
