### ISSUE TITLE
admin ui : project added but not showing up

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#63]
This morning, I have deployed the docker distribution based on latest version of `dashboard-plus-admin` branch. I reached _Projects > Import Projects_ and added https://github.com/docdoku/docdoku-plm.

At a first glance on submit it looks to work fine, I'm redirected to the project list as usual. The problem is I don't see the project in the list.

I've been investigating by looking into mongodb:

```
> db.projects.find( { "name" : "docdoku-plm" }, { full_name:1 } )
{ "_id" : "6103f6e5-da11-490e-b1b1-bd38630d5987", "full_name" : "docdoku/docdoku-plm" }
```

**Comment by ambpro** [comment]
The https://github.com/docdoku/docdoku-plm project is imported successfully on both the mongodb database and shown on scava dashboard UI:
<a href="https://ibb.co/g4gvXD1"><img src="https://i.ibb.co/g4gvXD1/docdoku-plm.jpg" alt="docdoku-plm" border="0"></a><br>
<a href="https://ibb.co/N24hkWJ"><img src="https://i.ibb.co/N24hkWJ/docdoku-plm-dtabase.jpg" alt="docdoku-plm-dtabase" border="0"></a>

**Comment by mhow2** [comment]
hi @ambpro, but what did you do to make it working ?

**Comment by mhow2** [comment]
@ambpro : but it seems you didn't have any existing project when you did your test.
Could you try on our instance please ?  http://wacke.ow2.org:5601

**Comment by ambpro** [comment]
Nothing special, I follow the traditional process to import a project and there you go!
About the existing project, I ignored the dump restore process in the docker build time because it take a lot of time.

**Comment by MarcioMateus** [comment]
@ambpro I would like to have you testing the import of a new project with the data dump. Something is not working as expected.

I imported a new project and a record project record was creates in ´scava´ database under the ´projects´ collection.

However, this new project does not appear on the adminstration-dashboard which makes impossible to start the analysis process.

A slight off-topic question: Is there a REST API to create a analysis task for a project?
