### ISSUE TITLE
error 500 on 8086/administration/projects

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#74]
## context and first indications
Yesterday, I have deployed a scava instance from scratch.

this morning, I got to the admin UI. First I've been able to find my way to the projects list but then bumped on an error when try importing a new one:

![screenshot_2018-12-07 crossminer administration](https://user-images.githubusercontent.com/9987241/49641472-8609a580-fa10-11e8-81dd-de08c82bdfc4.png)
The save button became grey and nothing happen.
I did see an error 500 (I don't have the response details but I think it the same as below).

## the current issue
A couple of hours later, I go to admin UI again (from a fresh browser session). It this point I'm not even able to get the list of projects (the list at `/project` is empty).
When I take a look at the trafic, I see the following:

![2018-12-07_001](https://user-images.githubusercontent.com/9987241/49641630-00d2c080-fa11-11e8-803b-713f413403d2.png)

The response detail for the error 500 above is : 
`{"timestamp":1544176878931,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"Read timed out"}`

I am available for further info. The instance is still running in the current state for now.

**Comment by mhow2** [comment]
Hi Amin,
Thank you for taking care of that one. I just deployed from your branch, we'll see. Notice that `zuul.socket-timeout-millis: 60000` uses the char `:` instead of `=`, unsure if it could be an issue.

**Comment by ambpro** [comment]
Hello @mhow2, sorry for the syntax error, I pushed a hotfixing in [here](https://github.com/crossminer/scava-deployment/commit/b7d92952be1154a2b27addaac8dac05b83063ef3)
