### ISSUE TITLE
Usability: start/end dates in task creation UI are misleading

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#76]
When creating a new analysis task, the start/end fields for the task are not clear as for their purpose. One would believe that it's the time that the task itself will run, whereas it seems it is the time range of the analysis that is impacted. 

Can we add a short text/description to help people understand what the fields are about?

**Comment by mhow2** [comment]
Yes I submit to this. start/end dates meaning should be more explicit. @ambpro told me some days ago he would have a look at the wording with @aabherve.

**Comment by borisbaldassari** [comment]
@mhow2 the labels have been changed, and it's good for me. Are you ok to close this issue?

**Comment by mhow2** [comment]
Yes thanks !
