### ISSUE TITLE
Projects are not being analysed

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#79]
After a fresh install, many projects are imported in the db and show up in the Admin UI > Projects page.
Some of them are updated or in progress, but the workers are empty. Some projects are still in the 'Not Defined' state, even after one day or more. You can check that out on the ci4 instance if you'd like.

![image](https://user-images.githubusercontent.com/5849071/49937501-2bbc8900-fed7-11e8-8c11-ca1fabb75eac.png)

**Comment by mhow2** [comment]
Same observation. @aabherve, @ambpro could you have a look ?

**Comment by ambpro** [comment]
I guess it's probably an issue related to the data dumps provided the scava-deployment. I'll provide an up-to-date version of projecst data dumps asap.

**Comment by borisbaldassari** [comment]
Not sure it's the same problem, but it's still happening on ci4 (updated today). Only one worker actually works, and no pending task is shown -- although there are pending tasks on another project. I don't know if the worker is stuck on the current analysis -- how could we tell?

![Capture du 2019-08-02 16-53-11](https://user-images.githubusercontent.com/5849071/62378943-2be0c600-b546-11e9-9bd9-92018c84c508.png)
![Capture du 2019-08-02 16-53-27](https://user-images.githubusercontent.com/5849071/62378948-2daa8980-b546-11e9-9fbd-b8e908d91c56.png)

**Comment by MarcioMateus** [comment]
Hi @borisbaldassari. If I am not mistaken you only have on worker running (`w1`). The other `worker1` is only a data structure created when you import the dumps without any worker instance associated with it.

When you start the platform with the docker-compose we are only creating the worker `w1`.

If you want to you more workers you need do uncomment the `oss-slave` service, which will create the worker `w2`.
https://github.com/crossminer/scava-deployment/blob/73122acebbef8ce04cb7e717289cf951d9c42e16/docker-compose-build.yml#L58

**Comment by borisbaldassari** [comment]
Can't be reproduced anymore, closing the issue.
