### ISSUE TITLE
Instance looses its data, Admin UI shows no project/worker

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava#81]
After a couple of days running, the instance doesn't answer anymore to requests on the various APIs (8182) and in the admin UI. When going into the admin UI, the projects and workers menu items are empty.

![image](https://user-images.githubusercontent.com/5849071/49988663-dd12fb80-ff77-11e8-91f4-07d88277a5a1.png)

![image](https://user-images.githubusercontent.com/5849071/49988678-e9975400-ff77-11e8-9380-a8f2e3a28e6a.png)

**Comment by borisbaldassari** [comment]
Note: the dashboard still shows some data, although it is incomplete.

**Comment by mhow2** [comment]
Hi @borisbaldassari it happened to me too. Could you have a look at the container's logs ? You can also try to hit the `metric-platform` directly at port 8182 to see if the API's online or not.

**Comment by borisbaldassari** [comment]
Ah, sorry but I had to re-initiate everything because we really need a working instance for philippe's tests on the ide plugin. Can't try that anymore..

**Comment by borisbaldassari** [comment]
Wel I'm wondering if it's not linked to issue #57 .. i.e. it occurs after creating a task with a blank in its name.

**Comment by ambpro** [comment]
@borisbaldassari Could you please provide container's logs about this issue ?

**Comment by borisbaldassari** [comment]
@ambpro as mentioned in this thread the ci4 instance has been restarted (long ago), because it is a live, production-grade instance. We cannot keep it down too long (e.g. weeks for this issue) just for the sake of reproducibility (unfortunately). 

Furthermore:
* You can access the instance's logs on the portainer instance: http://ci4.castalia.camp:9000 
You should have received the credentials on the internal mailing list, if you can't find them please let me know (privately).
* As for the reproducibility of the issue (if you're talking about my last comment), you simply have to create a task with a space in its name, quite easy. ;-)

**Comment by borisbaldassari** [comment]
Cant reproduce it anymore, could be closed as far as I'm concerned. @mhow2 what do you think?
