### ISSUE TITLE
The Lib Search wizard don't look like SWT based

### ISSUE THREAD

**Issue by phkrief** [crossminer/scava#87]
The wizard used for the libraries search doesn't seem to use the same GUI framework as the rest of the IDE.
Is it on purpose?

Thx

**Comment by geryxyz** [comment]
We discussed the question of UI in person in Athen.

**Comment by phkrief** [comment]
Sure. Nevertheless, you could repeat your position in this issue. WDYT?
Thx

**Comment by geryxyz** [comment]
We concluded that the UI mostly created with JFace with the fallback to SWT. We choose this since it could provide a much richer user experience.
