### ISSUE TITLE
OpenAPI specification for SCAVA

### ISSUE THREAD

**Issue by geryxyz** [crossminer/scava#9]
We have started to working on the openAPI specification of the communication, based on the document you have sent and our previous implementations. We merged them to try to maintain the current functionalities of the plugin, so we have added some more new paths and models over the ones you have proposed. Currently, as far as we know the generator - which can create our client from the specification - has some limitations. These are the followings:
- It can't handle post requests.
- It can't handle that if the response of a request returns an array-like objects
- It can't resolve generic type references in other types

We attached the created specification (`crossmeter.json`).  
In order to be able to generate a client from it, we have changed the return type of requests that would return an array, to a specific type which contains an array. We attached this modified specification (`crossmeter_wrapped.json`) and the generated client (`org.eclipse.crossmeter.workflow.restmule.generated.client.crossmeter`) too.  
**Note:** Only the *GET* method requests are included in the project, since the generator skips the *POST* requests.

[OpenAPI_prototype.zip](https://github.com/crossminer/scava/files/1988116/OpenAPI_prototype.zip)

**Comment by geryxyz** [comment]
Dear @md2manoppello , @davidediruscio and @aabherve ,
please check our prototype implementation. We appreciate any constructive opinion.
Feel free to add (mention), or involve any other interested parties.

**Comment by davidediruscio** [comment]
@md2manoppello will shortly push the OpenAPI specification related to the methods of the KB. However, according to https://github.com/crossminer/scava/wiki/API-Gateway-Component only one client should be generated (to be used e.g., by the IDE) and should only refer to the methods of the API Gateway. Isn't?

**Comment by md2manoppello** [comment]
We have integrated Swagger and OpenApi specification on KB (accessible rispectively at /swagger-ui.html and /v2/api-docs). Now, KB automatically generate OpenAPI specification and swagger interface.
We attached the generated OpenAPI specification (api-docs.json) and generated java client (KB_client.zip).
[KB_OPENAPI.zip](https://github.com/crossminer/scava/files/2005405/KB_OPENAPI.zip)

**Comment by geryxyz** [comment]
@md2manoppello Thanks for the information. We will check your implementation, and if everything fine began to integrate into the plugin. How are we able to run the current version of the KB to test the integration? The tutorial at https://github.com/crossminer/scava/wiki/Docker-Ossmeter is up-to-date? Or do you have a more recent docker image at bay?

**Comment by borisbaldassari** [comment]
Not sure if that helps, but the KB is built on Jenkins and tests are run [1], so you might be able to peruse the process described in the Jenkins files [2].

[1] http://ci5.castalia.camp:8080/job/scava-knowledgebase/
[2] https://github.com/crossminer/scava/blob/dev/knowledge-base/org.eclipse.scava.knowledgebase/Jenkinsfile
