### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by tdegueul** [crossminer/scava#97]
Scava currently supports importing projects from GitHub, Eclipse, Google Code, Redmine, and SourceForge. There is no support for importing projects from GitLab yet.

To add support for GitLab, we shall:

- Define a data model for GitLab, inspired from the one for GitHub ([here](https://github.com/crossminer/scava/tree/edd43eb327405ef531501e5c9f879977ee43ac3b/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github)) which stores useful information about GitLab repos in Mongo
- Implement a new [`IImporter`](https://github.com/crossminer/scava/blob/edd43eb327405ef531501e5c9f879977ee43ac3b/metric-platform/platform/org.eclipse.scava.repository.model.importer/src/org/eclipse/scava/repository/model/importer/IImporter.java), `GitLabImporter`, built on the model of [`GitHubImporter`](https://github.com/crossminer/scava/blob/edd43eb327405ef531501e5c9f879977ee43ac3b/metric-platform/platform-extensions/org.eclipse.scava.repository.model.github.importer/src/org/eclipse/scava/repository/model/github/importer/GitHubImporter.java)
- Make sure that the [`ProjectImporter`](https://github.com/crossminer/scava/blob/edd43eb327405ef531501e5c9f879977ee43ac3b/metric-platform/platform/org.eclipse.scava.platform.client.api/src/org/eclipse/scava/platform/client/api/ProjectImporter.java) picks it up when a GitLab URL (what is that?) is entered.

Essentially, this means interacting with the [GitLab API](https://docs.gitlab.com/ce/api/) to gather information about the project (URL, name, description, commits, issues, code, etc), and store it to let the platform pick it up and compute the metrics.

**Comment by tdegueul** [comment]
This should have been (partially) fixed in 86c7184f3646ef371f896a71c2756394a5ea103f. @mhow2 can we close for now and open new dedicated issues whenever you encounter a problem with the GitLab connector?

**Comment by mhow2** [comment]
Hi @tdegueul , thank you for the update.
I did not encounter any problem so far. This being said, I think we might add the metadata for the issue tracker (bugTrackingSystems in mongo) so it can be used by the other partners. Tell me if what I'm saying is consistent. If yes I would open another issue with it.

**Comment by tdegueul** [comment]
You're right. 86c7184 only takes care of retrieving the source code and ignores any other data from the forge. This will have to be improved but I'd rather have a separate issue for that. Please feel free to open a new issue to track progress!
